function main111()
	local c = get_console()
	c:execute("disconnect")
end

function main6666666()
 game.start_tutorial("mov_desire_5")
end

function main22222()
--	level.add_pp_effector ("dead_zone.ppe", 1001, true)
	level.set_pp_effector_factor(1001, 0.01)
end

-- run_string alife():create("medkit", db.actor:position(), db.actor:level_vertex_id(),db.actor:game_vertex_id())

function get_task_info(task_id, fmt)
	local _info = GetTextureInfo(task_id..fmt, "default_task_icon"..fmt)
	local r = _info:get_rect()
	r.x2 = r.x2-r.x1
	r.y2 = r.y2-r.y1
	return _info:get_file_name(), r
end

function main123()
	local a,b = get_task_info("kill_gunslinger","_small")
	db.actor:give_game_news("task state changed", a, b, 0, 0)
	
--	db.actor:give_talk_message("trader", "ui\\ui_icons_task",Frect():set(300,100,50,50),"iconed_trade_info")
--	db.actor:give_talk_message("Превед", "trader", "ui\\ui_icons_task",Frect():set(300,100,50,50),"iconed_trade_info")
--	db.actor:give_talk_message("Превед", "trader", "trader", "ui\\ui_icons_task",Frect():set(300,100,50,50),"iconed_trade_info")
--	db.actor:give_game_news("превед", "ui\\ui_icons_task", Frect():set(300,100,50,50),0,0)
--	db.actor:give_game_news("превед","trader", "ui\\ui_icons_task", Frect():set(300,100,50,50),0,0)
--	db.actor:give_game_news("trader","trader","trader", "ui\\ui_icons_task", Frect():set(300,100,50,50),0,0)
end


--snd_radar_stop	= sound_object([[ambient\cooling_stop]])
function _main()
	local radius = 30
	local ang    = 45
	local dir    = vector_rotate_y( db.actor:direction(), ang )
	level.spawn_phantom(db.actor:position():add( dir:mul(radius) ))
end
function main222222222222222()
	db.actor:disable_info_portion("esc_trader_newbie") 
	db.actor:disable_info_portion("esc_trader_tutorial_chosen") 
end

function main1111()
--	local news_text = "%c<255,160,160,160>" .. "Задание выполнено" .. "\\n" .. "%c<default>" .. "Информация о винтовке FN-2000 а также куча всякой лабуды типа убить долбаного стрелка или помочь сраному раненому"
	local news_text = game.translate_string("escape_trader_start_dialog_511")

	db.actor:give_game_news(news_text, "ui\\ui_pop_up_active_back", Frect():set(0,0,16,16), 0, 0)

end

function main_e()
--	local info = "test_andy_info" 
--	db.actor:give_info_portion(info) 
--	alife():create("wpn_binoc", db.actor:position(), db.actor:level_vertex_id(),db.actor:game_vertex_id())		
	
	if _G._b_flag==0 then 
		printf("restore")
		db.actor:restore_weapon()
		_G._b_flag = 1
	else
		printf("hide")
		db.actor:hide_weapon()
		_G._b_flag = 0
	end

--    alife():create ("wpn_knife", db.actor:position (), db.actor:level_vertex_id (),db.actor:game_vertex_id (), db.actor:id())


--	snd_radar_stop:play(db.actor, 0, sound_object.s2d)
--	level.add_complex_effector("effector_radar_stop", 12345)
	
--	db.actor:activate_slot(db.actor:active_slot()+1)

--	local news_text = "%c<255,160,160,160>" .. "Задание выполнено" .. "\\n" .. "%c<default>" .. "Информация о винтовке FN-2000 а также куча всякой лабуды типа убить долбаного стрелка или помочь сраному раненому"

--	db.actor:give_game_news(news_text, "ui\\ui_pop_up_active_back", Frect():set(0,0,16,16), 0, 0)
--	local news_text = "%c<255,160,160,160>" .. "Задание выполнено" .. "\\n" .. "%c<default>" .. "Информация о винтовке FN-2000 а также куча всякой лабуды типа убить долбаного стрелка или помочь сраному раненому"
--	local a,b = get_task_info("ui_iconsTotalSmall_found","_money")
--	b:set(83,0,49,26)
--	db.actor:give_game_news(news_text, a, b, 0, 0)

--	db.actor:give_talk_message(news_text, "ui\\ui_icons_task",Frect():set(300,100,50,50),"iconed_trade_info")

-- game.start_tutorial("credits_seq")
	
	
--	info = "tutorial_artefact_start" 
--	db.actor:give_info_portion(info) 
	
	
--	info = "encyclopedy_weapons_wpn_groza" 
--	db.actor:give_info_portion(info) 
	
--	info = "encyclopedy_weapons_wpn_fn2000"
--	db.actor:give_info_portion(info) 

--	info = "encyclopedy_mutant_flesh"
--	db.actor:give_info_portion(info) 

--	info = "encyclopedy_zone_artifact_af-cristall-flower"
--	db.actor:give_info_portion(info) 
end


function main()
   local h 		= hit()
   h.power 		= 0.02
   h.direction 	= vector():set(0, 0, 1)
   h.impulse 	= 0
   h.draftsman 	= db.actor
   h.type 		= hit.fire_wound
   db.actor:hit(h)

--burn  		1
--shock  		1
--strike  		1
--wound  		1
--fire_wound  	1
--radiation   	1
--telepatic   	1
--chemical_burn 1
--explosion

end
