
function main()
--	local ce = path_cam_effector("camera_effects\\prison_1.anm")
	_G.ce = _G.path_cam_effector("test.anm")
	level.add_cam_effector(_G.ce)	

--   local h = hit ()
--   h.power = 100
--   h.direction = vector():set(0, 0, 1)
--   h.impulse = 100
--   h.draftsman = db.actor
--   h.type = hit.fire_wound
--   db.actor:hit(h)
	
--local ce = path_cam_effector("test.anm")
--local ce = path_cam_effector("camera_effects\\earthquake.anm")


--local ce = _test.some_cam_effector(1.3,7.0,10.0,5.0)
--level.add_cam_effector(ce)

--	local info = "tutorial_artefact_start" 
--	db.actor:give_info_portion(info) 
   
end
