-- AGROPROM

function proceed()
    local actor = db.actor

	if actor:has_info("agr_krot_band") and
	   actor:object("krot_flash") ~= nil
	then
		actor:give_info_portion("agr_krot_band_done")
		actor:give_info_portion("agr_find_gunslinger_cache")
		level_tasks.set_task_state(task.completed, "agr_meet_krot_band", 0)
	end

	if actor:has_info("agroprom_military_case") and
	   actor:dont_has_info("agroprom_military_case_have") and
	   actor:object("quest_case_02") ~= nil
	then
		actor:give_info_portion("agroprom_military_case_have")
		level_tasks.set_task_state(task.completed, "agroprom_get_military_documents", 1)
	end

	if actor:has_info("agr_find_gunslinger_cache") and
	   actor:object("gunslinger_flash") ~= nil
	then
		actor:give_info_portion("agr_find_gunslinger_cache_done")
		level_tasks.set_task_state(task.completed, "agroprom_find_gunslinger_cache", 0)
	end

	if actor:dont_has_info("agroprom_find_stalker_phantom") and
	   actor:object("gunslinger_flash") ~= nil
	then
		actor:give_info_portion("agroprom_find_stalker_phantom")
	end
end

function process_info_portion(info_id)
	if ( info_id == "agr_factory_assault_start" or info_id == "agr_warning_recieved" ) and
	       not level_tasks.is_map_spot_present (303, "agr_factory_skirmish1_location")
	then
		level_tasks.add_location(303, "agr_factory_skirmish1_location")
		return true

	elseif info_id == "agr_help_stalkers_done" then
		level_tasks.remove_location(303, "agr_factory_skirmish1_location")
		return true

	elseif info_id == "agr_help_stalkers_assault_dead" and db.actor:has_info( "agr_help_stalkers_done" ) then
--		actor:give_info_portion("agr_help_stalkers_done")
		level_tasks.set_task_state(task.completed, "agr_help_stalkers", 0)
		return true

	elseif info_id == "agr_help_stalkers_defence_dead" and db.actor:has_info( "agr_help_stalkers_done" ) then
--		actor:give_info_portion("agr_help_stalkers_done")
		level_tasks.set_task_state(task.fail, "agr_help_stalkers", 0)
		return true


	elseif info_id == "agr_krot_band" then
		level_tasks.add_location(302, "agr_krot_location")
		return true

	elseif info_id == "agr_krot_band_done" then
		level_tasks.remove_location(302, "agr_krot_location")
		return true

	elseif info_id == "agr_find_gunslinger_cache" then
		level_tasks.add_location(301, "agr_gunslinger_cache_location")
		return true

	elseif info_id == "agr_find_gunslinger_cache_done" then
		level_tasks.remove_location(301, "agr_gunslinger_cache_location")
		return true

	elseif info_id == "agroprom_military_case" then
		level_tasks.add_location(300, "agr_military_case_location")
		return true

	elseif info_id == "agroprom_military_case_have" then
		level_tasks.remove_location(300, "agr_military_case_location")
		level_tasks.add_location(500, "bar_barman_location")
		return true
	end

	return false
end
