
local object_list		= {}
local object_id_list	= {}
-----------------------------------------------------------------------------------
-- Test Definitions
-----------------------------------------------------------------------------------

object_list["test1"] = {
	"test1_dog1",
	"test1_dog2",
	"test1_dog3",
	"test1_dog4",
	"test1_dog5",
	"test1_dog6",
	"test1_dog7",
	"test1_dog8"
}

object_list["test2"] = {
	"test2_controller1"
}

object_list["test3"] = {
	"test3_controller1",
	"test3_flesh1",
	"test3_dog1",
	"test3_boar1"
}

object_list["test4"] = {
	"test4_dog1",
	"test4_dog2",
	"test4_dog3",
	"test4_dog4",
	"test4_dog5",
	"test4_dog6",
	"test4_dog7"
}

------------------------------------------------------------------------------
-- Services
------------------------------------------------------------------------------

-- Save id of object while loading
function save_object_id()
	for test_name, test_name_table in pairs(object_list) do
		local tab = {}
		for index, obj_name in pairs(test_name_table) do
			local obj =	level.debug_object(tostring(obj_name))
			if (obj ~= nil) then
				table.insert(tab,tonumber(obj:id()))
			end
		end
		object_id_list[tostring(test_name)] = tab
	end
end


-- Check if object online
function object_online(object_id)
	return (alife() == nil) or alife():object(object_id).online
end

-- Move all offline
function offline_all()
	for test_name, test_name_table in pairs(object_list) do
		for index, obj_name in pairs(test_name_table) do
			local obj =	 level.debug_object(tostring(obj_name))
			if ((obj ~= nil) and (object_online(obj:id()))) then
				alife():set_switch_online	(obj:id(),false)
				alife():set_switch_offline	(obj:id(),true)
			end
		end
	end
end


-- Move online objects that are in scene index 
function online_scene(index)
	local tab = object_id_list["test" .. tostring(index)];
	for index, obj_id in pairs(tab) do
		local obj =	alife():object(tonumber(obj_id))
		if (obj ~= nil) then
			alife():set_switch_online	(obj_id,true)
			alife():set_switch_offline	(obj_id,false)
		end
	end
end

------------------------------------------------------------------------------
-- Main function (called on level load)
------------------------------------------------------------------------------
function main()
	wait_game		(2000)
	save_object_id	()
	offline_all		()
end


------------------------------------------------------------------------------
-- Base Run function (load extern)
------------------------------------------------------------------------------
function r(index)
	offline_all		()
	online_scene	(index)
end

