
function main()

--	db.actor:give_info_portion("storyline_actor_start")
	
--	wait(10000)

--	db.actor:give_info_portion("test_andy_info")

--	printf("story_ids : %d", story_ids.INVALID_STORY_ID)
	printf("story_ids : %d", story_ids.Escape_blockpost_case)
--	printf("story_ids : %d", alife_simulator._0)
--	printf("story_ids : %d", alife_simulator._1)
--	printf("story_ids : %d", alife_simulator._2)
end






