
function main ()
--	db.actor:give_info_portion("agroprom_military_case")
	local object 	= level.debug_actor():give_info_portion("agroprom_military_case_have")
end

function _main ()

	local object 	= level.debug_object ("vagon")
	level.map_add_object_spot(object:id(), "enemy_location", "vagon4ik" )
	
	local object 	= level.debug_object ("level_prefix_m_car")
	level.map_add_object_spot(object:id(), "enemy_location", "tractor" )
	
	
end

