

function fe(item, parent)
	local p = parent:position()
	p.x = -31
	p.y = 1
	p.z = -61
	parent:drop_item(item,p)
end

function main ()
--	db.actor:give_info_portion("agroprom_military_case")
	local a 	= level.debug_actor()
	a:inventory_for_each(fe)
end

function _main ()

	local object 	= level.debug_object ("vagon")
	level.map_add_object_spot(object:id(), "enemy_location", "vagon4ik" )
	
	local object 	= level.debug_object ("level_prefix_m_car")
	level.map_add_object_spot(object:id(), "enemy_location", "tractor" )
	
	
end

