--[[------------------------------------------------------------------------------------------------------------------
Respawn binder
--------------------------------------------------------------------------------------------------------------------]]

function bind(obj)
	local ini = obj:spawn_ini()

	if not ini then
		return
	end

	obj:bind_object(respawn_binder(obj))
end

----------------------------------------------------------------------------------------------------------------------

class "respawn_binder" ( object_binder )

function respawn_binder:__init( obj ) super( obj )
end

function respawn_binder:net_spawn( server_object )
	if not object_binder.net_spawn( self, server_object ) then
		return false
	end

	-- получить ссылку на настоящий серверный объект
	self.se_respawn = alife():object( server_object.id )
	return true
end

function respawn_binder:net_destroy()
	object_binder.net_destroy( self )
end

function respawn_binder:update( delta )
	object_binder.update( self, delta )
	self.se_respawn:update()
end
