-- Кабан атакующий через дверь
-- Кабан - boar
-- Пути : boar_way1		-	просто бегаем
--		  boar_way2		-	точка у двери
-- Зоны : stalker_zone	-	срабатывает на приближение игрока 	
--		  zone_boar_attack	 срабатывает при приближении кабана и отпускает его


local boar = get_level_object ("boar")
local freed = false
	
function on_enter_pzone (zone, obj)
	zone:clear_callback (true)
	reset_action (boar, boar_attack.script_name ())
	action (boar, move (move.act_run, move.force_type, patrol ("boar_way2")), cond (cond.move_end))
end

function on_enter_bzone (zone, obj)
	sound_object ("monsters\\boar\\hit_0"):play_at_pos (obj, obj:position (), 0)
	sound_object ("material\\wood\\wood_crash1_hl2"):play_at_pos (obj, obj:position (), 0)
	boar:script (false, boar_attack.script_name ())
	zone:clear_callback (true)
	freed = true
	printf ("Boar freed")
end


function main ()

	local bzone = get_level_object ("zone_boar_attack")
	local pzone = get_level_object ("stalker_zone")
	
	pzone:set_callback (boar_attack.on_enter_pzone, true)
	bzone:set_callback (boar_attack.on_enter_bzone, true)
	
	boar:script (true, boar_attack.script_name ())
	action (boar, move (move.act_walk_fwd, move.default, patrol ("boar_way1")), cond (cond.move_end))
	
	local oldtime = game.time ()
	local wait_time = math.random (2000, 3000)

	while freed == false do 
	    if boar:action () then
		   if game.time () - oldtime >= wait_time then
		      oldtime = game.time ()
		      wait_time = math.random (2000, 3000)	
		      update_action (boar, boar_attack.script_name (), sound ("monsters\\boar\\Idle_1", "bip01_head", vector ():set (0, 0, 0), 
		   	   			  vector ():set (0, 0, 0), false))
		   end	   			  
		end   
		wait ()
	end	
	
	printf ("End of script")
	
end