function proceed()
    local actor = db.actor
	-- Dark valley
	if actor:dont_has_info("val_player_knows_password") and
	   actor:object("borov_flash") then
		actor:give_info_portion("val_player_knows_password") 
	end

	-- Laboratory X18
	if actor:dont_has_info("dar_password_info1") and
	   actor:object("dar_pass_flash") then
		actor:give_info_portion("dar_password_info1") 
	end
	
	if actor:dont_has_info("dar_password_info2") and
	   actor:object("dar_pass_document") then
		actor:give_info_portion("dar_password_info2") 
	end
	
	if actor:dont_has_info("dar_document1") and
	   actor:object("dar_document1") then
		actor:give_info_portion("dar_document1") 
	end
	
	if actor:dont_has_info("dar_document2") and
	   actor:object("dar_document2") then
		actor:give_info_portion("dar_document2") 
	end

	if actor:dont_has_info("dar_document3") and
	   actor:object("dar_document3") then
		actor:give_info_portion("dar_document3") 
		
		if actor:dont_has_info("dar_actor_got_docs") then
			actor:give_info_portion("dar_actor_got_docs") 
		end
		
	end
	
	if actor:dont_has_info("dar_document4") and
	   actor:object("dar_document4") then
		actor:give_info_portion("dar_document4") 

		if actor:dont_has_info("dar_actor_got_docs") then
			actor:give_info_portion("dar_actor_got_docs") 
		end

	end

	if actor:dont_has_info("dar_document5") and
	   actor:object("dar_document5") then
		actor:give_info_portion("dar_document5") 
		
		if actor:dont_has_info("dar_actor_got_docs") then
			actor:give_info_portion("dar_actor_got_docs") 
		end
		
	end
		
end

function process_map_spot(info_id)


	return false
end

function val_escort_set_fight(actor, npc)
	local st = utils.obj_by_sid(400)
	if not st or not st:alive() then
		return
	end

	--local ignore_actor = distance_between(actor, st) > 10
	
	npc:set_relation(game_object.enemy, st)
	st:set_relation(game_object.enemy, npc)

	npc:set_relation(game_object.enemy, actor)
	actor:set_relation(game_object.enemy, npc)
end
