--------------------------------------------------------------------------------------------------------
-- Dialog & InfoPortions Function
--------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------
-- Trader
--------------------------------------------------------------------------------------------------------
function trader_alredy_give_job(trader, actor)
	local actor = db.actor
	if (actor:has_info("esc_kill_bandits_quest_have") and actor:dont_has_info("esc_kill_bandits_quest_done")) or
	   (actor:has_info("agroprom_military_case") and actor:dont_has_info("agroprom_military_case_done"))
	then
		return true
	end
	return false 
end
function is_tutorial(trader, actor)
	return not db.actor:has_info("tutorial_end")
end
function is_not_tutorial(trader, actor)
 return not this.is_tutorial(trader, actor)
end

function trader_dont_give_job(first_speaker, second_speaker)
	return not trader_alredy_give_job(first_speaker, second_speaker)
end

function trader_dont_need_artefact(first_speaker, second_speaker)
	local actor = db.actor
	if (actor:has_info("esc_artefact1_need") and actor:dont_has_info("esc_artefact1_have")) or
	   (actor:has_info("esc_artefact2_need") and actor:dont_has_info("esc_artefact2_have")) or
	   (actor:has_info("esc_artefact3_need") and actor:dont_has_info("esc_artefact3_have"))
	then
		return true
	end
	return false 
end

function actor_have_needed_artefact1(first_speaker, second_speaker)
	local actor = db.actor
	if actor ~= nil and
	   (actor:has_info("esc_artefact1_need") and actor:dont_has_info("esc_artefact1_have")) and
	   (actor:object("af_vyvert") ~= nil)
	then
		return true
	else
		return false
	end
end

function actor_have_needed_artefact2(first_speaker, second_speaker)
	local actor = db.actor
	if actor ~= nil and
	   (actor:has_info("esc_artefact2_need") and actor:dont_has_info("esc_artefact2_have")) and
	   (actor:object("af_blood") ~= nil)
	then
		return true
	else
		return false
	end
end

function actor_have_needed_artefact3(first_speaker, second_speaker)
	local actor = db.actor
	if actor ~= nil and
	   (actor:has_info("esc_artefact3_need") and actor:dont_has_info("esc_artefact3_have")) and
	   (actor:object("af_medusa") ~= nil)
	then
		return true
	else
		return false
	end
end

function actor_has_something(first_speaker, second_speaker)
	local actor = db.actor
	if actor ~= nil and
	   (actor:object("af_blood") ~= nil) or
	   (actor:object("af_medusa") ~= nil) or
	   (actor:object("af_vyvert") ~= nil)
	then
		return true
	else
		return false
	end
end

function give_needed_artefact1(first_speaker, second_speaker)
	local artefact1 = first_speaker:object("af_vyvert")
	dialogs.relocate_item(second_speaker, artefact1, "out")
	dialogs.relocate_money(second_speaker, 1000, "in")
end

function give_needed_artefact2(first_speaker, second_speaker)
	local artefact2 = first_speaker:object("af_blood")
	dialogs.relocate_item(second_speaker, artefact2, "out")
	dialogs.relocate_money(second_speaker, 1000, "in")
end

function give_needed_artefact3(first_speaker, second_speaker)
	local artefact3 = first_speaker:object("af_medusa")
	dialogs.relocate_item(second_speaker, artefact3, "out")
	dialogs.relocate_money(second_speaker, 1000, "in")
end


function trader_need_artefact(first_speaker, second_speaker)
	return not trader_dont_need_artefact(first_speaker, second_speaker)
end


function trader_dont_has_job(first_speaker, second_speaker)
    if trader_need_free_factory(first_speaker, second_speaker) == false and
	   trader_need_military_case(first_speaker, second_speaker) == false
	then
		return true
	end
	return false
end

--' Escape tutorial artefact
function have_tutorial_artefact(first_speaker, second_speaker)
  	return first_speaker:object("af_blood_tutorial") ~= nil
end
function give_medkit(first_speaker, second_speaker)
	local medkit = first_speaker:object("medkit")
	if medkit ~= nil then
		dialogs.relocate_item(first_speaker, medkit, "in")
	else
		printf("ERROR: Escape trader dont has a medkit.")
	end
end
function give_tutorial_artefact(first_speaker, second_speaker)
	local artefact = first_speaker:object("af_blood_tutorial")
	dialogs.relocate_item(second_speaker, artefact, "out")
end


--' Meet fox
function have_fox_info(first_speaker, second_speaker)
  	return first_speaker:object("fox_flash") ~= nil
end

function give_flash_to_actor(npc, actor)
	local item = npc:object("fox_flash")
	if item then
		dialogs.relocate_item(npc, item, "in")
	end
end

--' fox help

function transfer_medikit_to_fox (player, wounded)
    local obj = player:object("medkit")
    dialogs.relocate_item(wounded, obj, "out")   
	wounded:set_relation(game_object.friend, player)
	db.actor:give_info_portion("escape_fox_heal")
end


--' Escape blockpost box
function have_blockpost_case(first_speaker, second_speaker)
  	return first_speaker:object("quest_case_01") ~= nil
end
function trader_need_blockpost_box(first_speaker, second_speaker)
	local actor = db.actor
    if actor ~= nil and
	   actor:has_info("escape_stalker_done") and
	   actor:dont_has_info("escape_blockpost_case")
	then
		return true
	end
	return false
end
function give_blockpost_case(first_speaker, second_speaker)
	local case = first_speaker:object("quest_case_01")
	dialogs.relocate_item(second_speaker, case, "out")
	dialogs.relocate_money(second_speaker, 2000, "in")
--	level_tasks.set_task_state(task.completed, "esc_blockpost_case_to_trader", 0)
end

--' Agroprom military case
function trader_need_military_case(first_speaker, second_speaker)
	local actor = db.actor
    if actor ~= nil and
	   actor:has_info("escape_stalker_done") and
	   actor:dont_has_info("agroprom_military_case")
	then
		return true
	end
	return false
end

--' Escape trader artefact
function have_artefact_from_fleshes(first_speaker, second_speaker)
	local actor = db.actor
	if actor ~= nil and
	   (actor:object("af_vyvert") ~= nil or
	   actor:object("af_gravi") ~= nil or
	   actor:object("af_gold_fish") ~= nil)
	then
		return true
	end
  	return false
end


--' Kill bandits on factory
function trader_need_free_factory(first_speaker, second_speaker)
	local actor = db.actor
    if actor ~= nil and
	   actor:has_info("tutorial_end") and
	   actor:dont_has_info("esc_kill_bandits_quest_have")
	then
		return true
	end
	return false
end

--' tutorial wounded in vagon
function wounded_need_help(first_speaker, second_speaker)
	local actor = db.actor
	return actor ~= nil and actor:dont_has_info( "tutorial_wounded_help" )
end

--' trader needs military documents
function trader_need_military_document(first_speaker, second_speaker)
	local actor = db.actor
    if actor ~= nil and
	   actor:has_info("escape_blockpost_case_done") and
	   actor:dont_has_info("agroprom_military_case")
	then
		return true
	end
	return false
end

--' trader dialog about docs from labx18
function actor_has_documents (actor, npc)
	if actor:object("dar_document4") then
		return true
	else
		return false
	end
end

function actor_give_docs_x18 (actor, npc)
	local obj = player:object("dar_document4")
	dialogs.relocate_item(npc, obj, "out")
	db.actor:disable_info_portion("esc_return")
end


function reward_docs_x18_small (actor, npc)
	dialogs.relocate_money(npc, 1000, "in")
end

function reward_docs_x18_normal (actor, npc)
	dialogs.relocate_money(npc, 2000, "in")
end



--' Wolf has a job
function wolf_dont_has_job(first_speaker, second_speaker)
    if wolf_need_dynamite(first_speaker, second_speaker) == false
	then
		return true
	end
	return false
end

function wolf_need_dynamite(first_speaker, second_speaker)
	local actor = db.actor
    if actor ~= nil and
	   actor:dont_has_info("escape_dynamite_start") and
	   actor:dont_has_info("escape_dynamite_have") and
	   actor:dont_has_info("escape_dynamite_done")
	then
		return true
	end
	return false
end
--function wolf_notify_meet(first_speaker, second_speaker)
--	level_tasks.set_task_state(task.completed, "esc_dinamit_to_volk", 1)
--end

--' WOLF
function has_novice_access(actor, npc)
	if db.actor then
		return db.actor:has_info("tutorial_wounded_help") or db.actor:has_info("tutorial_wounded_death")
	end
	return false
end
function not_has_novice_access(actor, npc)
	return not this.has_novice_access(actor, npc)
end
function need_wolf_greet(actor, npc)
	if db.actor then
		return db.actor:has_info("tutorial_wounded_help") and db.actor:dont_has_info("tutorial_wounded_volk_greet")
	end
	return false	
end
function not_need_wolf_greet(actor, npc)
	return not this.need_wolf_greet(actor, npc)
end

--' Escape dynamite for Wolf
function transfer_wolf_ammo_to_actor(first_speaker, second_speaker)
	local obj = first_speaker:object("af_medusa")
	if obj ~= nil then
		dialogs.relocate_item(first_speaker, obj, "in")
	end
end

function have_dynamite(first_speaker, second_speaker)
  	return first_speaker:object("dynamite") ~= nil
end
function give_dynamite(first_speaker, second_speaker)
	local case = first_speaker:object("dynamite")
	dialogs.relocate_item(second_speaker, case, "out")
	dialogs.relocate_money(second_speaker, 1000, "in")
--	level_tasks.set_task_state(task.completed, "esc_dinamit_to_volk", 0)
end

function assault_ready(first_speaker, second_speaker)
	return db.actor:has_info("assault_have_vodka")
end
function assault_dont_ready(first_speaker, second_speaker)
	return db.actor:dont_has_info("assault_have_vodka")
end
function assault_actor_have_vodka(first_speaker, second_speaker)
	return second_speaker:object("vodka") ~= nil
end
function assault_actor_dont_have_vodka(first_speaker, second_speaker)
	return not this.assault_actor_have_vodka(first_speaker, second_speaker)
end
function transfer_vodka_to_assault(first_speaker, second_speaker)
	local obj = first_speaker:object("vodka")
	dialogs.relocate_item(second_speaker, obj, "out")
end

--' Escape Wounded's flash
function wounded_give_flash(first_speaker, second_speaker)
	local wounded_flash = second_speaker:object("esc_wounded_flash")
	dialogs.relocate_item(second_speaker, wounded_flash, "in")
end

function have_wounded_flash(first_speaker, second_speaker)
  	return first_speaker:object("esc_wounded_flash") ~= nil
end

function give_wounded_flash(first_speaker, second_speaker)
	local wounded_flash = first_speaker:object("esc_wounded_flash")
	dialogs.relocate_item(second_speaker, wounded_flash, "out")
	dialogs.relocate_money(second_speaker, 250, "in")
end

--' Escape bandits factory
function give_factory_reward_trader(first_speaker, second_speaker)
	dialogs.relocate_money(second_speaker, 500, "in")
end

--' Kill killers raid
function give_reward_killers(first_speaker, second_speaker)
	dialogs.relocate_money(second_speaker, 2500, "in")
end
