--------------------------------------------------------------------------------------------------------
-- Dialog & InfoPortions Function
--------------------------------------------------------------------------------------------------------
function give_kalash_to_loser(first_speaker, second_speaker)
	local weap = first_speaker:object("wpn_ak74")
	first_speaker:transfer_item (weap, second_speaker)
	first_speaker:set_task_state(task.completed, "escape_novice_need_weapon", 0)
end
function give_toz_to_loser(first_speaker, second_speaker)
	local weap = first_speaker:object("wpn_toz34")
	first_speaker:transfer_item (weap, second_speaker)
	first_speaker:set_task_state(task.completed, "escape_novice_need_weapon", 0)
end
function haveAK(first_speaker, second_speaker)
	return( first_speaker:object("wpn_ak74") ~= nil )
end
function haveTOZ(first_speaker, second_speaker)
	return( first_speaker:object("wpn_toz34") ~= nil )
end

function bandits_dead(first_speaker, second_speaker)
    return(first_speaker:has_info("escape_factory_bandits_dead"))
end

function set_dialog_thank(first_speaker, second_speaker)
	first_speaker:set_start_dialog("escape_novice_thank_actor")
end

-- Trader
function have_blockpost_case(first_speaker, second_speaker)
	return( first_speaker:object("escape_blockpost_case") ~= nil )
end
function give_blockpost_case(first_speaker, second_speaker)
	local case = first_speaker:object("escape_blockpost_case")
	first_speaker:transfer_item (case, second_speaker)
	second_speaker:transfer_money (500, first_speaker)
	first_speaker:set_task_state(task.completed, "escape_blockpost_case", 0)
end
function trader_need_blockpost_box(first_speaker, second_speaker)
	local actor = level.actor()
       	if actor ~= nil and
	   actor:dont_has_info("escape_need_blockpost_case") and
	   actor:dont_has_info("escape_have_blockpost_case")
	then
		return true
	end
	return false
end
function trader_alredy_give_job(first_speaker, second_speaker)
	local actor = level.actor()
       	if actor ~= nil and
	   actor:has_info("escape_need_blockpost_case") and
	   actor:dont_has_info("escape_have_blockpost_case")
	then
		return true
	end
	return false
end
function trader_dont_has_job(first_speaker, second_speaker)
	local actor = level.actor()
       	if actor ~= nil and
	   (actor:has_info("escape_need_blockpost_case") or
	   actor:has_info("escape_have_blockpost_case"))
	then
		return true
	end
	return false
end