function main()

	stalker1 = get_level_object("stalker_1")
	stalker2 = get_level_object("stalker_2")

	actor   	= get_actor()

	wait(1000)			

	stalker1:script	(true,  freedom_test.script_name())
	stalker2:script	(true,  freedom_test.script_name())

    action (stalker1, move (move.standing, move.stand, move.line), anim (anim.free), cond (cond.time_end, 100000000))
	action (stalker2, move (move.crouch, move.stand, move.line,	anim (anim.free), cond (cond.time_end, 100000000))


	while true do
	    wait()
	end

			stalker1:script	(false,  freedom_test.script_name())
			stalker2:script	(false,  freedom_test.script_name())

end


