actor_entered = false
passed_time = 0
first_warning = 0

----------------------------------------------------------------------------------------------------------------
-- callback для проверки вхождения игрока в зону скрипта
----------------------------------------------------------------------------------------------------------------
function on_enter(zone,object)
  if script_zone_id == zone:id () and actor_id == object:id () then
    printf("actor entering in our zone")
    actor_entered = true
  end
end
----------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------
-- callback для проверки выхода игрока из зоны скрипта
----------------------------------------------------------------------------------------------------------------
function on_exit(zone,object)
  if script_zone_id == zone:id () and actor_id == object:id () then
    printf("actor exited in our zone")
    actor_entered = false
  end
end
----------------------------------------------------------------------------------------------------------------



----------------------------------------------------------------------------------------------------------------
-- ожидание, пока игрок умрет
----------------------------------------------------------------------------------------------------------------
function wait_for_kill_actor (actor)

	while true do
		  if actor.health <= 0 then
			 wait (2000)
			 prof_hrom_pust_trup_uberet:play_at_pos (stalker1, stalker1:position (), 0)
			 return 1
			 end
		  wait (500)
		  end	 	

end


----------------------------------------------------------------------------------------------------------------
-- сообщение от второго сталкера, что возникла проблема и атака сталкеров
----------------------------------------------------------------------------------------------------------------
function stalkers_attacked (actor)

	rainbow_hrom_u_nas_problema:play_at_pos (stalker2, stalker2:position (), 0)
	stalker1:script	(false, freedom00.script_name())
	stalker1:script	(true,  freedom00.script_name())

    action (stalker3, 
			move (move.standing, move.run, move.line, patrol ("outway")), 
			look (look.fire_point, actor),
			anim (anim.free), 
			cond (cond.move_end)
            )

    wait (1000)	
	stalker2:script	(false,  freedom00.script_name())
end

----------------------------------------------------------------------------------------------------------------
-- вызывается, если игрок находится в зоне скрипта
----------------------------------------------------------------------------------------------------------------
function actor_in_zone (actor)

-- если игрок уже получил предупреждение при первом входе в зону, то второго не будет
	if first_warning == 1 then
 	   prof_sam_naprosilsya:play_at_pos (stalker1, stalker1:position (), 0)
	   wait (1000)
	   stalker1:script	(false,  freedom00.script_name())
 	   stalker2:script	(false,  freedom00.script_name())
	   freedom00.wait_for_kill_actor (actor)	
	   return 1
	   end

-- первое предупреждение
	prof_eto_territoriya_svobodi:play_at_pos (stalker1, stalker1:position (),0)	
	passed_time = game.time ()
	first_warning = 1

-- флажок, для указания того, что rainbow уже произнес свой текст
	local first_say = 0
	
    while true do
          -- если игрок ушел, то выйдем из цикла
		  if actor_entered == false then return 0 end

		  -- посчитаем, сколько прошло времени	
		  local temptime = game.time () - passed_time	

          -- если Проф закончил болтовню, то второе предупреждение
		  if temptime > 6500 and temptime < 8000 then
			 if first_say == 0 then
				rainbow_ti_chto_gluhoy:play_at_pos (stalker2, stalker2:position (),0)	
	 			first_say = 1
			    end
			 end 

		  -- если было второе предупреждение, то выжидаем время
--		  if temptime > 8000 and temptime < 13000 then 
--			 break 
--			 end
			 
		  -- проверка сталкеров на повреждения
		  if stalker1.health < 1.0 or stalker2.health < 1.0 then
			 freedom00.stalkers_attacked (actor)
			 break
			 end 

		  -- время вышло - атакуем 
		  if temptime > 13000 then
			 prof_sam_naprosilsya:play_at_pos (stalker1, stalker1:position (), 0)
			 wait (1000)
			 break
             end

		  wait (500)	
		  end

--	stalker1:script	(false,  freedom00.script_name())
--	stalker2:script	(false,  freedom00.script_name())

--	freedom00.wait_for_kill_actor (actor)	
	return 1

end

----------------------------------------------------------------------------------------------------------------
-- основная функция скрипта
----------------------------------------------------------------------------------------------------------------
function main()

-- set stalkers for script control
	stalker1 = get_level_object("stalker_1")
	stalker2 = get_level_object("stalker_2")
	stalker3 = get_level_object("stalker_3")

--set callbacks for enter player to script zone
	zone  = level.object ("freedom_script_zone")
	zone:clear_callback(true)
  	zone:clear_callback(false)
    zone:set_callback (this.on_enter,true)
    zone:set_callback (this.on_exit,false)

	local actor   	= get_actor()

	script_zone_id = zone:id ()
	actor_id = actor:id ()

	stalker1:script	(true,  freedom00.script_name())
	stalker2:script	(true,  freedom00.script_name())

	stalker3:script (true, freedom00.script_name())

    action (stalker1, 
			move (move.standing, move.stand, move.line, patrol ("way0000")), 
			look (look.fire_point, actor),
			anim (anim.danger), 
			cond (cond.time_end, 100000000))

    action (stalker2, 
			move (move.standing, move.stand, move.line, patrol ("way0000")), 
			look (look.fire_point, actor), 
			anim (anim.danger), 
			cond (cond.time_end, 100000000))

    action (stalker3, 
			move (move.standing, move.stand, move.line, patrol ("outway")), 
			look (look.fire_point, actor), 
			anim (anim.free), 
			cond (cond.time_end, 100000000))

	wait (1000)

	while true
          do 
 		    if actor_entered == true then 
			   if freedom00.actor_in_zone (actor) == 1 then break end
			   end
 	  	    if stalker1.health < 1.0 or stalker2.health < 1.0 then
			   printf ("Attack !!")
			   freedom00.stalkers_attacked (actor)
			   break	
		  	   end
			wait (500)
		  end

	stalker1:script	(false,  freedom00.script_name())
	stalker2:script	(false,  freedom00.script_name())

	freedom00.wait_for_kill_actor (actor)	
end


