
function main()
	local f = getFS()
	local flist = f:file_list_open("$screenshots$",FS.FS_ListFiles)
	local f_cnt = flist:Size()
	
//	for	it=0, f_cnt-1 	do
	local it = 50
	local file		=	flist:GetAt(it)
	printf("file[%d]=%s",it,file)
	local pth = f:update_path("$screenshots$", file) 
	printf("full path=%s",pth)
	
	printf("file age is [%s]",f:get_file_age_str(pth))
	
	local file_struct = f:exist("$screenshots$", file)
	if file_struct~=nil then
	printf("name=%s;modif=%d",file_struct.name,file_struct.modif)
	end
		
//   end
	
	flist:Free()
end
