---------------------------------------
-- демонстрация работы FSM  
-- пример 01. FSM одного сталкера с двумя
-- состояниями	
---------------------------------------

-- функция перехода в первое состояние из нулевого
function if_see_actor(npc, fsm)
	if npc:see(actor) == true then
		-- да, условие выполнено, FSM перейдет в состояние 
		-- как только мы сделаем return true
		log("i saw a fucking actor")

		-- при переходе из нулевого состояния всегда 
		-- незабываем взять контроль скрипта над FSM
		fsm:set_script_control()

		log("setting action")
		--	задаем новое состояние сталкера
		action(                                                                                                       
	    		npc,
			  	move	(move.standing, move.walk,move.line,patrol("way0002")),
				sound	("nemedlenno","bip01_spine2",vector():set(0,0,0),vector():set(0,0,0),false),
				look	(look.fire_point, actor),
				anim	(anim.danger),
				cond	(cond.time_end, 100000)
		)

		return true
	end
	-- нет, условие не сработало, все оталось как есть
	return false
end

-- функция перехода из первого состояние в нулевое
function dont_see_actor(npc, fsm)
	if npc:see(actor) == false or !npc:action() then
		log("i lost a trace of this fucking actor")
		return true
	end

	return false
end


function main()
	log	("FSM demo 01")

	stalker00	= get_level_object("m_stalker_e0000")
	actor = get_actor()

	-- инициализация FSM сталкера
	local fsm_stalker = FSM(this.script_name(), stalker00)

	-- установка функций перехода 
	fsm_stalker:set_transition(0, 1, this.if_see_actor)
	fsm_stalker:set_transition(1, 0, this.dont_see_actor)

	-- запуск бесконечного цикла для одного FSM
	fsm_stalker:run_loop()
end