game_phases={
      GAME_PHASE_NONE						                          = 0,
      GAME_PHASE_INPROGRESS                               = 1,
      GAME_PHASE_PENDING                                     = 2,
      GAME_PHASE_TEAM1_SCORES                          = 3,
      GAME_PHASE_TEAM2_SCORES                          = 4,
      GAME_PHASE_TEAMS_IN_A_DRAW                    = 5

   --script events must start from 1000

}

