local t

function loadJob(sj, gname, type, squad, groups)
	if type == "test" then
		t = { section = "walker1",
			idle = 0,
			prior = 0, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "walker2",
			idle = 0,
			prior = 0, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "walker3",
			idle = 0,
			prior = 0, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	if type == "gar_bandits" then
		t = { section = "walker1@gar_bandits",
			idle = 0,
			prior = 3, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "walker2@gar_bandits",
			idle = 0,
			prior = 3, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "walker3@gar_bandits",
			idle = 0,
			prior = 3, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "kamp1@gar_bandits",
			idle = 0,
			prior = 1, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "kamp1@gar_bandits",
			idle = 0,
			prior = 1, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "kamp1@gar_bandits",
			idle = 0,
			prior = 1, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "kamp1@gar_bandits",
			idle = 0,
			prior = 1, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "kamp1@gar_bandits",
			idle = 0,
			prior = 1, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "walker1@gar_bandits_attack",
			idle = 0,
			prior = 5, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "walker2@gar_bandits_attack",
			idle = 0,
			prior = 5, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "walker3@gar_bandits_attack",
			idle = 0,
			prior = 5, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "walker4@gar_bandits_attack",
			idle = 0,
			prior = 5, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "walker5@gar_bandits_attack",
			idle = 0,
			prior = 5, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
	end
	if type == "gar_stalkers" then
		t = { section = "walker1@gar_stalkers",
			idle = 0,
			prior = 3, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "walker2@gar_stalkers",
			idle = 0,
			prior = 3, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "walker3@gar_stalkers",
			idle = 0,
			prior = 3, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "kamp1@gar_stalkers",
			idle = 0,
			prior = 1, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "kamp1@gar_stalkers",
			idle = 0,
			prior = 1, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)				
		t = { section = "kamp1@gar_stalkers",
			idle = 0,
			prior = 1, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)				
		t = { section = "kamp1@gar_stalkers",
			idle = 0,
			prior = 1, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)				
		t = { section = "kamp1@gar_stalkers",
			idle = 0,
			prior = 1, state = {0,1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "walker1@gar_stalkers_attack",
			idle = 0,
			prior = 5, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "walker2@gar_stalkers_attack",
			idle = 0,
			prior = 5, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "walker3@gar_stalkers_attack",
			idle = 0,
			prior = 5, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "walker4@gar_stalkers_attack",
			idle = 0,
			prior = 5, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "walker5@gar_stalkers_attack",
			idle = 0,
			prior = 5, state = {1},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
	end
----------------------------------------------------------------------------	
-- Garbage DOLG blockpost	
----------------------------------------------------------------------------	
	if type == "gar_dolg" then
		t = { section = "walker1@gar_dolg",
			idle = 0,
			prior = 3, state = {0},
			in_rest = "", out_rest = "gar_golg"
		}
		table.insert(sj, t)		
		t = { section = "walker2@gar_dolg",
			idle = 0,
			prior = 3, state = {1},
			in_rest = "", out_rest = "gar_golg"
		}
		table.insert(sj, t)		
		t = { section = "walker3@gar_dolg",
			idle = 0,
			prior = 3, state = {1},
			in_rest = "", out_rest = "gar_golg"
		}
		table.insert(sj, t)		
		t = { section = "kamp1@gar_dolg",
			idle = 0,
			prior = 0, state = {0},
			in_rest = "", out_rest = "gar_golg"
		}
		table.insert(sj, t)
		t = { section = "kamp1@gar_dolg",
			idle = 0,
			prior = 0, state = {0},
			in_rest = "", out_rest = "gar_golg"
		}
		table.insert(sj, t)				
		t = { section = "kamp1@gar_dolg",
			idle = 0,
			prior = 0, state = {0},
			in_rest = "", out_rest = "gar_golg"
		}
		table.insert(sj, t)				
		t = { section = "kamp1@gar_dolg",
			idle = 0,
			prior = 0, state = {0},
			in_rest = "", out_rest = "gar_golg"
		}
		table.insert(sj, t)				
		t = { section = "kamp1@gar_dolg",
			idle = 0,
			prior = 0, state = {0},
			in_rest = "", out_rest = "gar_golg"
		}
		table.insert(sj, t)		
		t = { section = "patrol1@gar_dolg",
			idle = 2 * 1000 * 60 * 60,
			prior = 8, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		t = { section = "follower1@gar_dolg",
			idle = 2 * 1000 * 60 * 60,
			prior = 4, state = {0},
			in_rest = "", out_rest = "",
			leader = "patrol1@gar_dolg"
		}
		table.insert(sj, t)		
		t = { section = "follower1@gar_dolg",
			idle = 2 * 1000 * 60 * 60,
			prior = 4, state = {0},
			in_rest = "", out_rest = "",
			leader = "patrol1@gar_dolg"
		}
		table.insert(sj, t)		
		t = { section = "zoneguard1@gar_dolg",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		
    end	    
----------------------------------------------------------------------------	
-- Garbage DOLG blockpost end
----------------------------------------------------------------------------	
	
	
	if type == "blockpost" then
		--t = { section = "patrol1@blockpost",
			--idle = 2 * 1000 * 60 * 60,
			--prior = 4, state = {0},
			--in_rest = "", out_rest = ""
		--}
		--table.insert(sj, t)		
		--t = { section = "follower1@blockpost",
			--idle = 2 * 1000 * 60 * 60,
			--prior = 4, state = {0},
			--in_rest = "", out_rest = "",
			--leader = self:nameStalker(patrol1@blockpost)
		--}
		--table.insert(sj, t)		
	end

	if type == "test1" then
		t = { section = "sleeper@test1",
			idle = 0,
			prior = 0, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
end

function loadStates(gname, type)
	if type == "test" or type == "test1" then
		return function(gulag)
			return 0
		end
	end

	if type == "blockpost" then
		return function(gulag)
			return 0
		end
	end
	if type == "gar_stalkers" or type == "gar_bandits" then
		return function(gulag)
			if gulag.state == 1 then return 1 end
			
			local actor = level.actor()
			local zone = level.object("gar_shooting")
			if actor ~= nil and zone ~= nil then
				local st = actor:position():distance_to(zone:position())
				printf("%s", st)
				if st < 10 then
					return 1
				else
					return 0
				end
			else
				return 0
			end
		end
	end	
end

function get_megafone(type, name)
	if type == "blockpost" then
		st = gramofon.m_gramofon(name.."_rupor", "blockpost_commander")
		st:event(0)
		return st
	end
	return nil
end