-----------------------------------------------------------------------
-- Ñîñòîÿíèÿ áàçû áàíäèòîâ
--    0 - íîğìàëüíîå ñîñòîÿíèå
--    2 - òğåâîãà
-----------------------------------------------------------------------

local state_normal = 0
local state_alarm = 1
local state_alarm_actor_inside = 2
local state_fight = 1

function load_job(sj, gname, type, squad, groups)
	if type == "val_lager_bandits" then
		return load_job_lager_bandits(sj, gname, type, squad, groups)
	elseif type == "val_monolith_base" then
		return load_job_monolith_base(sj, gname, type, squad, groups)
	elseif type == "val_war_soldiers" then
		return load_job_war_soldiers(sj, gname, type, squad, groups)
	elseif type == "val_dogs_nest1" then
		return load_job_dogs_nest1(sj, gname, type, squad, groups)
	elseif type == "val_dogs_nest2" then
		return load_job_dogs_nest2(sj, gname, type, squad, groups)
	elseif type == "val_fleshes_nest1" then
		return load_job_fleshes_nest1(sj, gname, type, squad, groups)
	elseif type == "val_fleshes_nest2" then
		return load_job_fleshes_nest2(sj, gname, type, squad, groups)
	elseif type == "val_boars_nest1" then
		return load_job_boars_nest1(sj, gname, type, squad, groups)
	elseif type == "val_boars_nest2" then
		return load_job_boars_nest2(sj, gname, type, squad, groups)
	end
	
	return
end

function lb_predicate1(obj) 
	return obj:profile_name() == "bandit_borov"
end

function lb_predicate2(obj) 
	return obj:profile_name() == "bandit_veteran"
end

function lb_predicate3(obj) 
	return obj:profile_name() == "bandit_general"
end

function load_job_lager_bandits(sj, gname, type, squad, groups)
	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 9 - ÁÎĞÎÂ
	-----------------------------------------------------------------------
	t = { section = "logic@val_lager_bandits_leader_normal",
		idle = 0,
		prior = 9, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_borov_restrictor",
		predicate = lb_predicate1
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_borov"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_leader_alarm",
		idle = 0,
		prior = 9, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_borov_restrictor",
		predicate = lb_predicate1
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_borov"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_leader_alarm",
		idle = 0,
		prior = 9, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_borov_restrictor",
		predicate = lb_predicate1
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_borov"
		            --end
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 8 - ÎÕĞÀÍÍÈÊÈ ÁÎĞÎÂÀ
	-----------------------------------------------------------------------
	t = { section = "logic@val_lager_bandits_bodyguard_normal1",
		idle = 0,
		prior = 8, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_building_restrictor",
		predicate = lb_predicate2
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_veteran"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_bodyguard_alarm1",
		idle = 0,
		prior = 8, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_building_restrictor",
		predicate = lb_predicate2
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_veteran"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_bodyguard_alarm1",
		idle = 0,
		prior = 8, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_building_restrictor",
		predicate = lb_predicate2
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_veteran"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_bodyguard_normal2",
		idle = 0,
		prior = 8, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_bodyguards_restrictor",
		predicate = lb_predicate2
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_veteran"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_bodyguard_alarm2",
		idle = 0,
		prior = 8, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_bodyguards_restrictor",
		predicate = lb_predicate2
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_veteran"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_bodyguard_alarm2",
		idle = 0,
		prior = 8, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_bodyguards_restrictor",
		predicate = lb_predicate2
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_veteran"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_bodyguard_normal3",
		idle = 0,
		prior = 8, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_bodyguards_restrictor",
		predicate = lb_predicate2
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_veteran"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_bodyguard_alarm3",
		idle = 0,
		prior = 8, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_bodyguards_restrictor",
		predicate = lb_predicate2
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_veteran"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_bodyguard_alarm3",
		idle = 0,
		prior = 8, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_bodyguards_restrictor",
		predicate = lb_predicate2
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_veteran"
		            --end
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 7 - ÑÈÄßÙÈÅ Â ÊÅÌÏÅ 1 ÂÎÇËÅ ÁÎĞÎÂÀ È Â ÊÅÌÏÅ 2 ÍÀ ÂÒÎĞÎÌ İÒÀÆÅ
	-----------------------------------------------------------------------
	t = { section = "logic@val_lager_bandits_kamp1_normal1",
		idle = 0,
		prior = 7, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_building_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp1_alarm1",
		idle = 0,
		prior = 7, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_building_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp1_alarm1",
		idle = 0,
		prior = 7, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_building_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp1_normal2",
		idle = 0,
		prior = 7, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_building_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp1_alarm2",
		idle = 0,
		prior = 7, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_building_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp1_alarm2",
		idle = 0,
		prior = 7, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_building_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp1_normal3",
		idle = 0,
		prior = 7, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_building_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp1_alarm3",
		idle = 0,
		prior = 7, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_building_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp1_alarm3",
		idle = 0,
		prior = 7, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_building_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp2_normal1",
		idle = 0,
		prior = 7, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp2_alarm1",
		idle = 0,
		prior = 7, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp2_alarm1",
		idle = 0,
		prior = 7, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp2_normal2",
		idle = 0,
		prior = 7, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp2_alarm2",
		idle = 0,
		prior = 7, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp2_alarm2",
		idle = 0,
		prior = 7, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp2_normal3",
		idle = 0,
		prior = 7, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp2_alarm3",
		idle = 0,
		prior = 7, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp2_alarm3",
		idle = 0,
		prior = 7, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp2_normal4",
		idle = 0,
		prior = 7, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp2_alarm4",
		idle = 0,
		prior = 7, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp2_alarm4",
		idle = 0,
		prior = 7, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)


	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 6 - ÁÀÍÄÈÒÛ ÍÀ ÂÎĞÎÒÀÕ
	-----------------------------------------------------------------------
	t = { section = "logic@val_lager_bandits_guard_normal1",
		idle = 0,
		prior = 6, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_side_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_guard_alarm1",
		idle = 0,
		prior = 6, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_side_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_guard_alarm1",
		idle = 0,
		prior = 6, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_side_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_guard_normal2",
		idle = 0,
		prior = 6, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_guard_alarm2",
		idle = 0,
		prior = 6, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_guard_alarm2",
		idle = 0,
		prior = 6, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 5 - ÏÀÒĞÓËÜÍÛÅ ÍÀ ÒÅĞĞÈÒÎĞÈÈ
	-----------------------------------------------------------------------
	t = { section = "logic@val_lager_bandits_patrol_normal1",
		idle = 0,
		prior = 5, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_side_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_patrol_alarm1",
		idle = 0,
		prior = 5, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_side_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_patrol_alarm1",
		idle = 0,
		prior = 5, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_main_side_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_patrol_normal2",
		idle = 0,
		prior = 5, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_patrol_alarm2",
		idle = 0,
		prior = 5, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_patrol_alarm2",
		idle = 0,
		prior = 5, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_patrol_normal3",
		idle = 0,
		prior = 5, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_patrol_alarm3",
		idle = 0,
		prior = 5, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_patrol_alarm3",
		idle = 0,
		prior = 5, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_patrol_normal4",
		idle = 0,
		prior = 5, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_patrol_alarm4",
		idle = 0,
		prior = 5, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_patrol_alarm4",
		idle = 0,
		prior = 5, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 4 - ÑÍÀÉÏÅĞÛ ÍÀ ÂÛØÊÀÕ
	-----------------------------------------------------------------------
	t = { section = "logic@val_lager_bandits_sniper_normal1",
		idle = 0,
		prior = 4, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sniper_alarm1",
		idle = 0,
		prior = 4, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sniper_alarm1",
		idle = 0,
		prior = 4, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sniper_normal2",
		idle = 0,
		prior = 4, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sniper_alarm2",
		idle = 0,
		prior = 4, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sniper_alarm2",
		idle = 0,
		prior = 4, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 3 - ÑÏßÙÈÅ ÁÀÍÄÈÒÛ
	-----------------------------------------------------------------------

	t = { section = "logic@val_lager_bandits_sleeper_normal1",
		idle = 0,
		prior = 3, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sleeper_alarm1",
		idle = 0,
		prior = 3, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sleeper_alarm1",
		idle = 0,
		prior = 3, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sleeper_normal2",
		idle = 0,
		prior = 3, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sleeper_alarm2",
		idle = 0,
		prior = 3, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sleeper_alarm2",
		idle = 0,
		prior = 3, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sleeper_normal3",
		idle = 0,
		prior = 3, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sleeper_alarm3",
		idle = 0,
		prior = 3, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sleeper_alarm3",
		idle = 0,
		prior = 3, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sleeper_normal4",
		idle = 0,
		prior = 3, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sleeper_alarm4",
		idle = 0,
		prior = 3, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_sleeper_alarm4",
		idle = 0,
		prior = 3, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 2 - ÁÀÍÄÈÒÛ Â 3-Ì ÊÅÌÏÅ
	-----------------------------------------------------------------------

	t = { section = "logic@val_lager_bandits_kamp3_normal1",
		idle = 0,
		prior = 2, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp3_alarm1",
		idle = 0,
		prior = 2, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp3_alarm1",
		idle = 0,
		prior = 2, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp3_normal2",
		idle = 0,
		prior = 2, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp3_alarm2",
		idle = 0,
		prior = 2, state = { state_alarm },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_lager_bandits_kamp3_alarm2",
		idle = 0,
		prior = 2, state = { state_alarm_actor_inside },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_lager_bandits_nedostroyka_restrictor",
		predicate = lb_predicate3
		            --function(obj) 
		            --	return obj:profile_name() == "bandit_general"
		            --end
	}
	table.insert(sj, t)

end

function mb_predicate(obj)
    local pname = obj:profile_name()
	return pname == "monolit_regular"
end

function load_job_monolith_base(sj, gname, type, squad, groups)
	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 4 - ÏÀÒĞÓËÈ ÍÀ ÒÅĞĞÈÒÎĞÈÈ
	-----------------------------------------------------------------------
	t = { section = "logic@val_monolith_base_patrol_normal1",
		idle = 0,
		prior = 4, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_patrol_normal2",
		idle = 0,
		prior = 4, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)
	
	t = { section = "logic@val_monolith_base_patrol_normal3",
		idle = 0,
		prior = 4, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_patrol_normal4",
		idle = 0,
		prior = 4, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_patrol_normal5",
		idle = 0,
		prior = 4, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_patrol_normal6",
		idle = 0,
		prior = 4, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 1 - ÏÅĞÂÛÉ ÊÅÌÏ
	-----------------------------------------------------------------------
	t = { section = "logic@val_monolith_base_kamp1_normal1",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp1_normal2",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp1_normal3",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp1_normal4",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 1 - ÂÒÎĞÎÉ ÊÅÌÏ
	-----------------------------------------------------------------------
	t = { section = "logic@val_monolith_base_kamp2_normal1",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp2_normal2",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp2_normal3",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp2_normal4",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 1 - ÒĞÅÒÈÉ ÊÅÌÏ
	-----------------------------------------------------------------------
	t = { section = "logic@val_monolith_base_kamp3_normal1",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp3_normal2",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp3_normal3",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp3_normal4",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 3 - ×ÅÒÂÅĞÒÛÉ ÊÅÌÏ
	-----------------------------------------------------------------------
	t = { section = "logic@val_monolith_base_kamp4_normal1",
		idle = 0,
		prior = 3, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp4_normal2",
		idle = 0,
		prior = 3, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp4_normal3",
		idle = 0,
		prior = 3, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp4_normal4",
		idle = 0,
		prior = 3, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp4_normal5",
		idle = 0,
		prior = 3, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 2 - ÏßÒÛÉ ÊÅÌÏ
	-----------------------------------------------------------------------
	t = { section = "logic@val_monolith_base_kamp5_normal1",
		idle = 0,
		prior = 2, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp5_normal2",
		idle = 0,
		prior = 2, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj) 
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp5_normal3",
		idle = 0,
		prior = 2, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj)
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)

	t = { section = "logic@val_monolith_base_kamp5_normal4",
		idle = 0,
		prior = 2, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_main_building_restrictor",
		predicate = mb_predicate
		            --function(obj)
		            --	return obj:profile_name() == "monolit_regular"
		            --end
	}
	table.insert(sj, t)
end

function ws_predicate(obj)
    local pname = obj:profile_name()
	return pname == "soldier_regular" or pname == "soldier_specnaz"
end

function load_job_war_soldiers(sj, gname, type, squad, groups)
	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 4 - ÏÀÒĞÓËÈ ÍÀ ÒÅĞĞÈÒÎĞÈÈ
	-----------------------------------------------------------------------
	t = { section = "logic@val_war_soldiers_patrol_normal1",
		idle = 0,
		prior = 4, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight1",
		idle = 0,
		prior = 4, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_patrol_normal2",
		idle = 0,
		prior = 4, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)
	
	t = { section = "logic@val_war_soldiers_fight2",
		idle = 0,
		prior = 4, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_patrol_normal3",
		idle = 0,
		prior = 4, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight3",
		idle = 0,
		prior = 4, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_patrol_normal4",
		idle = 0,
		prior = 4, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight4",
		idle = 0,
		prior = 4, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_patrol_normal5",
		idle = 0,
		prior = 4, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight5",
		idle = 0,
		prior = 4, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_patrol_normal6",
		idle = 0,
		prior = 4, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight6",
		idle = 0,
		prior = 4, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 1 - ÏÅĞÂÛÉ ÊÅÌÏ
	-----------------------------------------------------------------------
	t = { section = "logic@val_war_soldiers_kamp1_normal1",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight7",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp1_normal2",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight8",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp1_normal3",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight9",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp1_normal4",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight10",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 1 - ÂÒÎĞÎÉ ÊÅÌÏ
	-----------------------------------------------------------------------
	t = { section = "logic@val_war_soldiers_kamp2_normal1",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight11",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp2_normal2",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight12",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp2_normal3",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight13",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp2_normal4",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight14",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 1 - ÒĞÅÒÈÉ ÊÅÌÏ
	-----------------------------------------------------------------------
	t = { section = "logic@val_war_soldiers_kamp3_normal1",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight15",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp3_normal2",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight16",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp3_normal3",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight17",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp3_normal4",
		idle = 0,
		prior = 1, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight18",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 3 - ×ÅÒÂÅĞÒÛÉ ÊÅÌÏ
	-----------------------------------------------------------------------
	t = { section = "logic@val_war_soldiers_kamp4_normal1",
		idle = 0,
		prior = 3, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight19",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp4_normal2",
		idle = 0,
		prior = 3, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight20",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp4_normal3",
		idle = 0,
		prior = 3, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight21",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp4_normal4",
		idle = 0,
		prior = 3, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight22",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp4_normal5",
		idle = 0,
		prior = 3, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight23",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	-----------------------------------------------------------------------
	-- ÏĞÈÎĞÈÒÅÒ 2 - ÏßÒÛÉ ÊÅÌÏ
	-----------------------------------------------------------------------
	t = { section = "logic@val_war_soldiers_kamp5_normal1",
		idle = 0,
		prior = 2, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight24",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp5_normal2",
		idle = 0,
		prior = 2, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight25",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp5_normal3",
		idle = 0,
		prior = 2, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight26",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_kamp5_normal4",
		idle = 0,
		prior = 2, state = { state_normal },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_war_soldiers_main_building_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)

	t = { section = "logic@val_war_soldiers_fight27",
		idle = 0,
		prior = 1, state = { state_fight },
		squad = squad, group = groups[1],
		in_rest = "", out_rest = "val_monolith_base_war_restrictor",
		predicate = ws_predicate
	}
	table.insert(sj, t)
end

function load_job_dogs_nest1(sj, gname, type, squad, groups)
	t = { section = "logic@val_dogs_nest1", 
		idle = 0,
		prior = 5, state = {0}, squad = squad, group = groups[0],
		in_rest = "", out_rest = "val_dogs_nest1_small_restr"
	}
	table.insert(sj, t)

	t = { section = "logic@val_dogs_nest1", 
		idle = 0,
		prior = 5, state = {1}, squad = squad, group = groups[0],
		in_rest = "", out_rest = "val_dogs_nest1_big_restr"
	}
    table.insert(sj, t)
end

function load_job_dogs_nest2(sj, gname, type, squad, groups)
	t = { section = "logic@val_dogs_nest2", 
		idle = 0,
		prior = 5, state = {0}, squad = squad, group = groups[0],
		in_rest = "", out_rest = "val_dogs_nest2_small_restr"
	}
	table.insert(sj, t)

	t = { section = "logic@val_dogs_nest2", 
		idle = 0,
		prior = 5, state = {1}, squad = squad, group = groups[0],
		in_rest = "", out_rest = "val_dogs_nest1_big_restr"
	}
    table.insert(sj, t)
end

function load_job_fleshes_nest1(sj, gname, type, squad, groups)
	t = { section = "logic@val_fleshes_nest1", 
		idle = 0,
		prior = 5, state = {0}, squad = squad, group = groups[0],
		in_rest = "", out_rest = "val_fleshes_nest1_small_restr"
	}
	table.insert(sj, t)

	t = { section = "logic@val_fleshes_nest1", 
		idle = 0,
		prior = 5, state = {1}, squad = squad, group = groups[0],
		in_rest = "", out_rest = "val_fleshes_nest1_big_restr"
	}
    table.insert(sj, t)
end

function load_job_fleshes_nest2(sj, gname, type, squad, groups)
	t = { section = "logic@val_fleshes_nest2", 
		idle = 0,
		prior = 5, state = {0}, squad = squad, group = groups[0],
		in_rest = "", out_rest = "val_fleshes_nest2_small_restr"
	}
	table.insert(sj, t)

	t = { section = "logic@val_fleshes_nest2", 
		idle = 0,
		prior = 5, state = {1}, squad = squad, group = groups[0],
		in_rest = "", out_rest = "val_fleshes_nest1_big_restr"
	}
    table.insert(sj, t)
end

function load_job_boars_nest1(sj, gname, type, squad, groups)
	t = { section = "logic@val_boars_nest1", 
		idle = 0,
		prior = 5, state = {0}, squad = squad, group = groups[0],
		in_rest = "", out_rest = "val_boars_nest1_small_restr"
	}
	table.insert(sj, t)

	t = { section = "logic@val_boars_nest1", 
		idle = 0,
		prior = 5, state = {1}, squad = squad, group = groups[0],
		in_rest = "", out_rest = "val_boars_nest1_big_restr"
	}
    table.insert(sj, t)
end

function load_job_boars_nest2(sj, gname, type, squad, groups)
	t = { section = "logic@val_boars_nest2", 
		idle = 0,
		prior = 5, state = {0}, squad = squad, group = groups[0],
		in_rest = "", out_rest = "val_boars_nest2_small_restr"
	}
	table.insert(sj, t)

	t = { section = "logic@val_boars_nest2", 
		idle = 0,
		prior = 5, state = {1}, squad = squad, group = groups[0],
		in_rest = "", out_rest = "val_boars_nest1_big_restr"
	}
    table.insert(sj, t)
end

function load_states(gname, type)
	if type == "val_lager_bandits" then
		return check_state_lager_bandits(gulag)
	elseif type == "val_monolith_base" then
		return check_state_monolith_base(gulag)
	elseif type == "val_war_soldiers" then
		return check_state_war_soldiers(gulag)
	elseif type == "val_dogs_nest1" then  
	    return check_state_dogs_nest1(gulag)
	elseif type == "val_dogs_nest2" then  
	    return check_state_dogs_nest2(gulag)
	elseif type == "val_fleshes_nest1" then  
	    return check_state_fleshes_nest1(gulag)
	elseif type == "val_fleshes_nest2" then  
	    return check_state_fleshes_nest2(gulag)
	elseif type == "val_boars_nest1" then  
	    return check_state_boars_nest1(gulag)
	elseif type == "val_boars_nest2" then  
	    return check_state_boars_nest2(gulag)
	end

	return nil
end

function check_state_lager_bandits(gulag)
	return function(gulag)
		for k,v in gulag.Object do
			local enemy = v:best_enemy()
			if enemy ~= nil then
				enemy_type = get_clsid(enemy)
				if enemy_type == clsid.actor and
				   utils.npc_in_zone(db.actor, db.zone_by_name["val_lager_bandits_restrictor"]) then
					return state_alarm_actor_inside
				end
				if enemy_type == clsid.actor or
  	   			   enemy_type == clsid.soldier or
	   			   enemy_type == clsid.script_stalker or
   				   enemy_type == clsid.trader
   				then
   					gulag.alarm_start = game.get_game_time()
   					return state_alarm
   				end
			end
		end		
		
		if gulag.alarm_start == nil or game.get_game_time():diffSec(gulag.alarm_start) > 900 then
			return state_normal -- îáû÷íîå ñîñòîÿíèå
		end
		return state_alarm -- òğåâîãà
	end
end

function check_state_monolith_base(gulag)
	return function(gulag)
		return state_normal
	end
end

function check_state_war_soldiers(gulag)
	return function(gulag)
	    if db.actor:has_info("val_opendoor_chase_start") then
		    return state_normal
		end
		return state_fight
	end
end

function check_state_dogs_nest1(gulag)
	return function(gulag)
		local t = db.zone_by_name["val_dogs_nest1_restr_big"] -- èìÿ áîëüøîãî ğåñòğ.
		if t and db.actor then
			if t:inside(db.actor:position()) then
				return 1
			else
				return 0
			end
		else
			return gulag.state
		end
	end
end

function check_state_dogs_nest2(gulag)
	return function(gulag)
		local t = db.zone_by_name["val_dogs_nest2_restr_big"] -- èìÿ áîëüøîãî ğåñòğ.
		if t and db.actor then
			if t:inside(db.actor:position()) then
				return 1
			else
				return 0
			end
		else
			return gulag.state
		end
	end
end

function check_state_fleshes_nest1(gulag)
	return function(gulag)
		local t = db.zone_by_name["val_fleshes_nest1_restr_big"] -- èìÿ áîëüøîãî ğåñòğ.
		if t and db.actor then
			if t:inside(db.actor:position()) then
				return 1
			else
				return 0
			end
		else
			return gulag.state
		end
	end
end

function check_state_fleshes_nest2(gulag)
	return function(gulag)
		local t = db.zone_by_name["val_fleshes_nest2_restr_big"] -- èìÿ áîëüøîãî ğåñòğ.
		if t and db.actor then
			if t:inside(db.actor:position()) then
				return 1
			else
				return 0
			end
		else
			return gulag.state
		end
	end
end

function check_state_boars_nest1(gulag)
	return function(gulag)
		local t = db.zone_by_name["val_boars_nest1_restr_big"] -- èìÿ áîëüøîãî ğåñòğ.
		if t and db.actor then
			if t:inside(db.actor:position()) then
				return 1
			else
				return 0
			end
		else
			return gulag.state
		end
	end
end

function check_state_boars_nest2(gulag)
	return function(gulag)
		local t = db.zone_by_name["val_boars_nest2_restr_big"] -- èìÿ áîëüøîãî ğåñòğ.
		if t and db.actor then
			if t:inside(db.actor:position()) then
				return 1
			else
				return 0
			end
		else
			return gulag.state
		end
	end
end

function checkStalker(npc_community, gulag_type)
	if gulag_type == "val_lager_bandits" then
		return npc_community == "bandit"
	end
	
	if gulag_type == "val_monolith_base" then
	    return npc_community == "monolith"
	end    

	if gulag_type == "val_war_soldiers" then
	    return npc_community == "military"
	end    

	return false
end

function checkMonster(npc_community, gulag_type)
    if gulag_type == "val_dogs_nest1" then
	    return npc_community == "dog"
    end

    if gulag_type == "val_dogs_nest2" then
	    return npc_community == "dog"
    end

    if gulag_type == "val_fleshes_nest1" then
	    return npc_community == "flesh"
    end

    if gulag_type == "val_fleshes_nest2" then
	    return npc_community == "flesh"
    end

    if gulag_type == "val_boars_nest1" then
	    return npc_community == "boar"
    end

    if gulag_type == "val_boars_nest2" then
	    return npc_community == "boar"
    end

    return false
end
