function loadJob(sj, gname, type)
--'-----------------------------------------------------------------------------------------
--' ESCAPE BLOCKPOST
--'-----------------------------------------------------------------------------------------
	if type == "blockpost" then
		--' STATE 0
		t = { name = "patrol",
			object = nil, begin = nil, idle = 6*60*60*1000,
			prior = 8, state = 0,
			squad = 0, group = 1,
			in_rest = "", out_rest = "",
			patrol_path = gname.."_patrol_0",
			escape_path = gname.."_escape_0" }
		table.insert(sj, t)			
		t = { name = "follower",
			object = nil, begin = nil, idle = 6*60*60*1000,
			prior = 7, state = 0,
			squad = 0, group = 1,
			in_rest = "", out_rest = "",
			leader_name = nil,
			escape_path = gname.."_escape_0" }
		table.insert(sj, t)			
		t = { name = "follower",
			object = nil, begin = nil, idle = 6*60*60*1000,
			prior = 7, state = 0,
			squad = 0, group = 1,
			in_rest = "", out_rest = "",
			leader_name = nil,
			escape_path = gname.."_escape_0" }
		table.insert(sj, t)			
		t = { name = "guard",
			object = nil, begin = nil, idle = 0,
			prior = 10, state = 0,
			squad = 0, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			running = false, search_light = nil,
			path_main = gname.."_guard_center",
			path_hideout = gname.."_guard_center" }
		table.insert(sj, t)			
		t = { name = "guard",
			object = nil, begin = nil, idle = 0,
			prior = 6, state = 0,
			squad = 0, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			running = false, search_light = nil,
			path_main = gname.."_guard_left",
			path_hideout = gname.."_guard_left" }
		table.insert(sj, t)			
		t = { name = "guard",
			object = nil, begin = nil, idle = 0,
			prior = 6, state = 0,
			squad = 0, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			running = false, search_light = nil,
			path_main = gname.."_guard_right",
			path_hideout = gname.."_guard_right" }
		table.insert(sj, t)
		t = { name = "guard",
			object = nil, begin = nil, idle = 0,
			prior = 9, state = 0,
			squad = 0, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			running = false, search_light = nil,
			path_main = gname.."_guard_light",
			path_hideout = gname.."_guard_light" }
		table.insert(sj, t)			
		t = { name = "guard",
			object = nil, begin = nil, idle = 0,
			prior = 5, state = 0,
			squad = 0, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			running = false, search_light = nil,
			path_main = gname.."_gb_left",
			path_hideout = gname.."_gb_left" }
		table.insert(sj, t)
		t = { name = "guard",
			object = nil, begin = nil, idle = 0,
			prior = 5, state = 0,
			squad = 0, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			running = false, search_light = nil,
			path_main = gname.."_gb_right",
			path_hideout = gname.."_gb_right" }
		table.insert(sj, t)
		t = { name = "sleeper",
			object = nil, begin = nil, idle = 0,
			prior = 1, state = 0,
			squad = 1, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			path_main = gname.."_sleep_1"}
		table.insert(sj, t)			
		t = { name = "sleeper",
			object = nil, begin = nil, idle = 0,
			prior = 1, state = 0,
			squad = 1, group = 0,
			path_main = gname.."_sleep_2"}
		table.insert(sj, t)			
		t = { name = "sleeper",
			object = nil, begin = nil, idle = 0,
			prior = 1, state = 0,
			squad = 1, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			path_main = gname.."_sleep_3"}
		table.insert(sj, t)			
		t = { name = "sleeper",
			object = nil, begin = nil, idle = 0,
			prior = 1, state = 0,
			squad = 1, group = 0,
			path_main = gname.."_sleep_4"}
		table.insert(sj, t)			
		t = { name = "sleeper",
			object = nil, begin = nil, idle = 0,
			prior = 1, state = 0,
			squad = 1, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			path_main = gname.."_sleep_5"}
		table.insert(sj, t)			
		t = { name = "sleeper",
			object = nil, begin = nil, idle = 0,
			prior = 1, state = 0,
			squad = 1, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			path_main = gname.."_sleep_6"}
		table.insert(sj, t)			

		--' STATE 1
		t = { name = "patrol",
			object = nil, begin = nil, idle = 6*60*60*1000,
			prior = 8, state = 1,
			squad = 0, group = 1,
			in_rest = "", out_rest = "",
			patrol_path = gname.."_patrol_0",
			escape_path = gname.."_escape_0" }
		table.insert(sj, t)			
		t = { name = "follower",
			object = nil, begin = nil, idle = 6*60*60*1000,
			prior = 7, state = 1,
			squad = 0, group = 1,
			in_rest = "", out_rest = "",
			leader_name = nil,
			escape_path = gname.."_escape_0" }
		table.insert(sj, t)			
		t = { name = "follower",
			object = nil, begin = nil, idle = 6*60*60*1000,
			prior = 7, state = 1,
			squad = 0, group = 1,
			in_rest = "", out_rest = "",
			leader_name = nil,
			escape_path = gname.."_escape_0" }
		table.insert(sj, t)			
		t = { name = "guard",
			object = nil, begin = nil, idle = 0,
			prior = 10, state = 1,
			squad = 0, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			running = false, search_light = nil,
			path_main = gname.."_guard_center",
			path_hideout = gname.."_guard_center" }
		table.insert(sj, t)			
		t = { name = "guard",
			object = nil, begin = nil, idle = 0,
			prior = 9, state = 1,
			squad = 0, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			running = false, search_light = nil,
			path_main = gname.."_guard_light",
			path_hideout = gname.."_guard_light" }
		table.insert(sj, t)			
		t = { name = "guard",
			object = nil, begin = nil, idle = 0,
			prior = 6, state = 1,
			squad = 0, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			running = false, search_light = nil,
			path_main = gname.."_alarm_left",
			path_hideout = gname.."_alarm_left" }
		table.insert(sj, t)			
		t = { name = "guard",
			object = nil, begin = nil, idle = 0,
			prior = 6, state = 1,
			squad = 0, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			running = false, search_light = nil,
			path_main = gname.."_alarm_right",
			path_hideout = gname.."_alarm_right" }
		table.insert(sj, t)			
		t = { name = "guard",
			object = nil, begin = nil, idle = 0,
			prior = 6, state = 1,
			squad = 0, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			running = false, search_light = nil,
			path_main = gname.."_alarm_house",
			path_hideout = gname.."_alarm_house" }
		table.insert(sj, t)			
		t = { name = "guard",
			object = nil, begin = nil, idle = 0,
			prior = 5, state = 1,
			squad = 0, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			running = false, search_light = nil,
			path_main = gname.."_alarm_center",
			path_hideout = gname.."_alarm_center" }
		table.insert(sj, t)		
		t = { name = "sleeper",
			object = nil, begin = nil, idle = 0,
			prior = 1, state = 1,
			squad = 1, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			path_main = gname.."_sleep_1"}
		table.insert(sj, t)			
		t = { name = "sleeper",
			object = nil, begin = nil, idle = 0,
			prior = 1, state = 1,
			squad = 1, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			path_main = gname.."_sleep_2"}
		table.insert(sj, t)			
		t = { name = "sleeper",
			object = nil, begin = nil, idle = 0,
			prior = 1, state = 1,
			squad = 1, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			path_main = gname.."_sleep_3"}
		table.insert(sj, t)			
		t = { name = "sleeper",
			object = nil, begin = nil, idle = 0,
			prior = 1, state = 1,
			squad = 1, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			path_main = gname.."_sleep_4"}
		table.insert(sj, t)			
		t = { name = "sleeper",
			object = nil, begin = nil, idle = 0,
			prior = 1, state = 1,
			squad = 1, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			path_main = gname.."_sleep_5"}
		table.insert(sj, t)			
		t = { name = "sleeper",
			object = nil, begin = nil, idle = 0,
			prior = 1, state = 1,
			squad = 1, group = 0,
			in_rest = gname.."_zone", out_rest = "",
			path_main = gname.."_sleep_6"}
		table.insert(sj, t)			
	end
end

function loadStates(st, gname, type, calculateState)
	if type == "blockpost" then
		t = { id = 1,
		    timeout = 1*60*60*1000 }
		table.insert(st, t)			
		t = { id = 2,
		    timeout = 1*60*60*1000 }
		table.insert(st, t)			
		calculateState = function(obj)
			for k,v in obj
				enemy = v:best_enemy()
				if enemy ~= nil then
					enemy_type = get_clsid(enemy)
					if 	enemy_type == clsid.actor or
	  	   				enemy_type == clsid.soldier or
		   				enemy_type == clsid.stalker or
	   					enemy_type == clsid.trader
	   				then
	   					return 1
	   				end
				end
			end
			return 0
		end
	end
end
