local t = {}

function load_job(sj, gname, type, squad, groups)
	-- Yantar Zombies
	if type == "yantar_zombies" then
		t = { section = "logic@yantar_zombies_kamp1",
			idle = 0,
			prior = 9, state = {1}, squad = squad, group = groups[2],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp1",
			idle = 0,
			prior = 9, state = {1}, squad = squad, group = groups[2],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp1",
			idle = 0,
			prior = 9, state = {1}, squad = squad, group = groups[2],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp1",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1}, squad = squad, group = groups[2],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp1",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1}, squad = squad, group = groups[2],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp1",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1}, squad = squad, group = groups[2],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    

		t = { section = "logic@yantar_zombies_kamp2",
			idle = 0,
			prior = 9, state = {1}, squad = squad, group = groups[3],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp2",
			idle = 0,
			prior = 9, state = {1}, squad = squad, group = groups[3],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp2",
			idle = 0,
			prior = 9, state = {1}, squad = squad, group = groups[3],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp2",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1}, squad = squad, group = groups[3],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp2",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1}, squad = squad, group = groups[3],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp2",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1}, squad = squad, group = groups[3],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    

		t = { section = "logic@yantar_zombies_kamp3",
			idle = 0,
			prior = 9, state = {1}, squad = squad, group = groups[4],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp3",
			idle = 0,
			prior = 9, state = {1}, squad = squad, group = groups[4],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp3",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1,2}, squad = squad, group = groups[4],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp3",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1,2}, squad = squad, group = groups[4],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp3",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1,2}, squad = squad, group = groups[4],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    

		t = { section = "logic@yantar_zombies_kamp3",
			idle = 0,
			prior = 9, state = {1}, squad = squad, group = groups[4],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp3",
			idle = 0,
			prior = 9, state = {1}, squad = squad, group = groups[4],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp3",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1,2}, squad = squad, group = groups[4],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp3",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1,2}, squad = squad, group = groups[4],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp3",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1,2}, squad = squad, group = groups[4],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    

		t = { section = "logic@yantar_zombies_kamp4",
			idle = 0,
			prior = 9, state = {1}, squad = squad, group = groups[5],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp4",
			idle = 0,
			prior = 9, state = {1}, squad = squad, group = groups[5],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp4",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1,2}, squad = squad, group = groups[5],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp4",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1,2}, squad = squad, group = groups[5],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_kamp4",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 5, state = {1,2}, squad = squad, group = groups[5],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    



		t = { section = "logic@yantar_zombies_walker",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 7, state = {1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_walker",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 7, state = {1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_walker",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 7, state = {1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_walker",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 7, state = {1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		t = { section = "logic@yantar_zombies_walker",
			idle = 0, timeout = math.random(10,20)*60*1000,
			prior = 7, state = {1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		    
		
	end
end

function load_states(gname, type)
    if type == "yantar_zombies" then
		return function(gulag)
			return 1
		end
    end

end



--------------------------------------------------------------------------
-- Dynamic ltx
--------------------------------------------------------------------------
function load_ltx(gname, type)
	return nil
end

function checkStalker(npc_community, gulag_type)
	if gulag_type == "yantar_zombies" then
		return npc_community == "zombied"
	end
end

function checkMonster(npc_community, gulag_type)
end