
--прожектора на вышках при нападении на базу
-- Прожектора -  projector1, projector2
-- Точки для прожекторов:
--					project1_point1
--					project1_point2
--					project2_point1
--					project2_point2
--					project2_point3
-- Скриптовая зона для переключения прожекторов - projector_zone

local intruder = nil
local called = false
local alarm = sound_object ("Scripts\\rolik\\alarm")
local source = get_level_object ("projector1")

function on_enter (zone, obj)
	intruder = obj
	zone:clear_callback (true)
	alarm:play_at_pos(source, source:position (), 0, sound_object.looped)
end

function main ()

    local proj1 = get_level_object ("projector1")
    proj1:script (true, m_attack_wave21.script_name ())
    action (proj1, object (object.turn_off), cond (cond.time_end, time_infinite))
    
    local proj2 = get_level_object ("projector2")
    proj2:script (true, m_attack_wave21.script_name ())
    action (proj2, object (object.turn_off), cond (cond.time_end, time_infinite))

    local initz = get_level_object ("projector_zone")
    initz:set_callback (m_attack_wave21.on_enter, true)
    
    while true do wait () end
    
--  local points1 = {patrol ("project1_point1"):point (0), patrol ("project1_point2"):point (0)}
--  local points2 = {patrol ("project2_point1"):point (0), patrol ("project2_point2"):point (0), patrol ("project2_point3"):point (0)}

--  local proj1 = classes.Projector (get_level_object ("projector1"), 0.52, 0.22, m_attack_wave21.script_name (), points1, false, nil)
--  local proj2 = classes.Projector (get_level_object ("projector2"), 0.52, 0.22, m_attack_wave21.script_name (), points2, false, nil)
  

--  while true do
--      proj1:process ()
--      proj2:process ()
--      if called == false then
--      	 if intruder ~= nil then 
--      	 	proj1:set_target (intruder)
--      	 	called = true
--      	 end
--      end	  	
--      wait ()
--  end


end