class "Easy"
function Easy:__init()
	self.monsters   = {}
    self.amount     = 0
end

function Easy:insert( obj )
    if( obj == nil ) then
    	printf( "Insert nil object" )
        return
    end
    table.insert( self.monsters, obj )
    self.amount = self.amount + 1
end

function Easy:execute()
	if( self.amount == 0 ) then
    	return false
    end

	for i = 1, self.amount do
    	self.monsters[i]:execute()
    end

    for i = self.amount,1,-1  do
        if( self.monsters[i]:check_completed() ) then
            self.monsters[i]:finalize()
            table.remove( self.monsters, i )
        	printf( "Remove member from table" )
            self.amount = self.amount - 1
        end
    end

    return true
end

function Easy:finalize()
	if( self.amount == 0 ) then return end
	for i = self.amount, 1, -1 do
        printf( "Remove %d from table", i )
        self.monsters[i]:finalize()
        table.remove( self.monsters, i )
    end
end

