--------------------------------------------------------------------------------
class "stateSound"
function stateSound:__init( script_name, mem )
    self.scr_name   = script_name
    self.memory     = mem
end

--------------------------------------------------------------------------------

function stateSound:initialize()
	self.memory.npc:script( true, self.scr_name )
end

--------------------------------------------------------------------------------

function stateSound:finalize()
	self.memory.sound.time = 0
    self.memory.npc:script( false, self.scr_name )
end

--------------------------------------------------------------------------------

function stateSound:execute()
	printf( "stateSound executed" )
	if( self.memory.npc:action() == nil ) then
        if( self.memory.sound == nil ) then printf( "Sound is nil" ) end
        if( self.memory.sound.position == nil ) then printf( "Sound position is nil" ) end

        action( self.memory.npc, move( move.walk_fwd, self.memory.sound.position ), cond( cond.move_end ) )
    end
end

--------------------------------------------------------------------------------

function stateSound:can_start()
    return ( ( self.memory.sound.time ~= 0 ) and ( self.memory.npc:position():distance_to( self.memory.sound.position ) > 1 ) )
end

--------------------------------------------------------------------------------

function stateSound:check_complited()
    return ( ( self.memory.sound.time == 0 ) or ( self.memory.npc:position():distance_to( self.memory.sound.position ) < 1 ) )
end

--------------------------------------------------------------------------------

function stateSound:update()
	reset_action( self.memory.npc, self.scr_name )
end

--------------------------------------------------------------------------------

function stateSound:id()
	return 5
end