function process_tasks ()
    local actor = db.actor
    
    process_crazy ()
    
    
    if db.actor:has_info ("mil_lukash_dead") and 
       db.actor:has_info ("mil_sniper_dead") and
       db.actor:has_info ("mil_dolg_mission_complete") and 
       db.actor:dont_has_info ("mil_dolg_task_complete") then
       news_manager.send_tip (db.actor, "mil_mission_complete", nil, "dolg")
       db.actor:give_info_portion ("mil_dolg_task_complete")
    end        
    
    if db.actor:has_info ("mil_courier_report") then
       if level_tasks.is_map_spot_present (707, "mil_lukash_location") == true then
          level_tasks.remove_location (707, "mil_lukash_location")
       end   
    end
    
    if db.actor:has_info ("mil_fblockpost_spot") then
       if db.actor:dont_has_info ("mil_fblockpost_spot_set") then
          db.actor:give_info_portion ("mil_fblockpost_spot_set")
          level_tasks.add_location (724, "mil_fblockpost_location")
       end
    end
    
    if db.actor:has_info ("mil_fblockpost_spot") then
       if db.actor:has_info ("mil_fblockpost_spot_remove") then
          level_tasks.remove_location_safe (724, "mil_fblockpost_location")
          db.actor:disable_info_portion ("mil_fblockpost_spot_remove")
       end
    end      
            
    	
	if actor:object ("bandit_flash") then 
	   db.actor:give_info_portion("mil_bandit_flash_get")  
	end

	if actor:object ("ugrum_flash") then 
	   db.actor:give_info_portion("mil_ugrum_flash_get")  
	end

	if actor:object ("max_flash") then 
	   db.actor:give_info_portion("mil_max_owner_flash_get")  
	end
	
	if actor:object ("wpn_rg-6") then 
	   db.actor:give_info_portion("mil_rg6_gain")  
	end	
	
	if db.actor:dont_has_info ("mil_fblockpost_final") then
	   if db.actor:has_info ("mil_fblockpost_quest") then
          if db.actor:has_info ("mil_fblockpost_quest_complete") then
	         level_tasks.set_task_state (task.completed, "mil_blockpost_job", 0) 
	         db.actor:give_info_portion ("mil_fblockpost_final")
	      end
	      if db.actor:has_info ("mil_fblockpost_quest_fail") then
             level_tasks.set_task_state (task.fail, "mil_blockpost_job", 0) 
             db.actor:give_info_portion ("mil_fblockpost_final")
	      end   
	   end   
	end   
	
	process_khutor () 
end

function process_crazy ()
    if db.actor:object ("crazy_flash") == nil then return end
    
    if db.actor:dont_has_info ("mil_max_flash_get") then
       db.actor:give_info_portion ("mil_max_flash_get")
    end   
    
    if db.actor:has_info ("mil_max_job") then
       level_tasks.set_task_state (task.completed, "mil_mad_job", 1)
    end    
end


function process_khutor ()
    -- если квест был выполнен или провален, то выйдем    
    if db.actor:has_info ("mil_courier_quest_failed") or db.actor:has_info ("mil_courier_quest_complete") then
       return
    end    
    -- если не стартован квест стукача, то выходим
    if db.actor:dont_has_info ("mil_courier_quest") then 
       return 
    end
    
    if level_tasks.is_map_spot_present (710, "mil_courier_location") == false then
--    if db.actor:has_info ("mil_courier_quest_failed") == false and db.actor:has_info ("mil_courier_quest_complete")  == false then
       level_tasks.add_location (710, "mil_courier_location")
       level_tasks.remove_location (707, "mil_lukash_location")
    end   
    
    if db.actor:has_info ("mil_courier_in_khutor_zone") then -- если курьер на хуторе, то...
       --if db.actor:dont_has_info ("mil_courier_khutor_leave") then  -- если он его не покинул...
          if db.actor:has_info ("mil_actor_in_khutor_zone") then --если и актер на хуторе
             if db.actor:dont_has_info ("mil_courier_quest_part1") then   
                if db.actor:has_info ("mil_courier_call") then
                   level_tasks.set_task_state (task.completed, "mil_courier_job", 1) -- первая часть выполнена
                   db.actor:give_info_portion ("mil_courier_quest_part1")
                end   
             end   
             if db.actor:has_info ("mil_ara_entered") then --если в это время явился Ара, то и вторая часть выполнена
                if db.actor:dont_has_info ("mil_courier_quest_part2") then   
                   level_tasks.set_task_state (task.completed, "mil_courier_job", 2)
                   db.actor:give_info_portion ("mil_courier_quest_part2")
                end
             end   
          end 
       --end
    end
    
    if db.actor:has_info ("mil_courier_dead") then  -- если курьер умер
       if db.actor:has_info ("mil_courier_quest_part1") then -- если первая часть задачи выполнена
          if db.actor:dont_has_info ("mil_courier_quest_part3") then   
             level_tasks.set_task_state (task.completed, "mil_courier_job", 3) -- третья часть выполнена
             db.actor:give_info_portion ("mil_courier_quest_part3")
          end   
       else   
          level_tasks.set_task_state (task.fail, "mil_courier_job", 0) --иначе, задача провалена
          db.actor:give_info_portion ("mil_courier_quest_failed")
          level_tasks.remove_location (710, "mil_courier_location")
          level_tasks.add_location (707, "mil_lukash_location")
       end
    end   
    
    if db.actor:has_info ("mil_ara_dead") then
       if db.actor:has_info ("mil_courier_quest_part2") then -- если вторая часть задачи выполнена
          if db.actor:dont_has_info ("mil_courier_quest_part4") then   
             level_tasks.set_task_state (task.completed, "mil_courier_job", 4) -- третья часть выполнена
             db.actor:give_info_portion ("mil_courier_quest_part4")
          end   
       else
          level_tasks.set_task_state (task.fail, "mil_courier_job", 0) --иначе, задача провалена
          db.actor:give_info_portion ("mil_courier_quest_failed")
          level_tasks.remove_location (710, "mil_courier_location")
          level_tasks.add_location (707, "mil_lukash_location")
       end
    end
    
    if db.actor:has_info ("mil_ara_leave") then      
       level_tasks.set_task_state (task.fail, "mil_courier_job", 0) --если Ара ушел, то задача провалена
       db.actor:give_info_portion ("mil_courier_quest_failed")
       level_tasks.remove_location (710, "mil_courier_location")
       level_tasks.add_location (707, "mil_lukash_location")
    end   
          
    if db.actor:has_info ("mil_courier_quest_part1") and 
       db.actor:has_info ("mil_courier_quest_part2") and
       db.actor:has_info ("mil_courier_quest_part3") and
       db.actor:has_info ("mil_courier_quest_part4") then
       level_tasks.set_task_state (task.completed, "mil_courier_job", 0)
       db.actor:give_info_portion ("mil_courier_quest_complete")
       db.actor:disable_info_portion ("mil_courier_dead")
       db.actor:disable_info_portion ("mil_ara_dead")
       db.actor:disable_info_portion ("mil_courier_quest_part1")
       db.actor:disable_info_portion ("mil_courier_quest_part2")
       db.actor:disable_info_portion ("mil_courier_quest_part3")
       db.actor:disable_info_portion ("mil_courier_quest_part4")
       db.actor:disable_info_portion ("mil_courier_in_khutor_zone")
       db.actor:disable_info_portion ("mil_actor_in_khutor_zone_inside")
       db.actor:disable_info_portion ("mil_courier_khutor_leave")
       level_tasks.remove_location (710, "mil_courier_location")
       level_tasks.add_location (707, "mil_lukash_location")
    end       
       
             --if db.actor:has_info ("mil_actor_in_khutor_zone_inside") then
             --level_tasks.set_task_state (task.completed, "mil_courier_job", 2)
             --db.actor:give_info_portion ("mil_courier_quest_part2")
          --end
       --else
          --if db.actor:has_info ("mil_actor_in_khutor_zone") then
             --level_tasks.set_task_state (task.completed, "mil_courier_job", 0)
             --db.actor:give_info_portion ("mil_courier_quest_part1")
          --else
             --level_tasks.set_task_state (task.fail, "mil_courier_job", 0)
             --db.actor:give_info_portion ("mil_courier_quest_failed")
             --level_tasks.remove_location (710, "mil_courier_location")
             --level_tasks.add_location (707, "mil_lukash_location")
             --return
          --end 
          --if db.actor:has_info ("mil_actor_in_khutor_zone_inside") then
             --level_tasks.set_task_state (task.completed, "mil_courier_job", 2)
             --db.actor:give_info_portion ("mil_courier_quest_part2")
             --level_tasks.remove_location (710, "mil_courier_location")
             --level_tasks.add_location (707, "mil_lukash_location")
          --else   
             --level_tasks.set_task_state (task.fail, "mil_courier_job", 0)
             --db.actor:give_info_portion ("mil_courier_quest_failed")
             --level_tasks.remove_location (710, "mil_courier_location")
             --level_tasks.add_location (707, "mil_lukash_location")
             --return
          --end
       --end   
    --end      
    
    --if db.actor:has_info ("mil_courier_dead") then
       --if db.actor:dont_has_info ("mil_courier_in_khutor_zone") then
          --level_tasks.set_task_state (task.fail, "mil_courier_job", 0)
          --db.actor:give_info_portion ("mil_courier_quest_failed")
          --level_tasks.remove_location (710, "mil_courier_location")
          --level_tasks.add_location (707, "mil_lukash_location")
          --return
       --else
          --level_tasks.set_task_state (task.completed, "mil_courier_job", 3)
          --level_tasks.remove_location (710, "mil_courier_location")
          --level_tasks.add_location (707, "mil_lukash_location")
       --end   
    --end
    
--    if db.actor:has_info ("mil_courier_dead") and 
       --db.actor:has_info ("mil_courier_quest_part1") and
       --db.actor:has_info ("mil_courier_quest_part2") then
       --level_tasks.set_task_state (task.completed, "mil_courier_job", 0)
       --db.actor:give_info_portion ("mil_courier_quest_complete")
       --db.actor:disable_info_portion ("mil_courier_dead")
       --db.actor:disable_info_portion ("mil_courier_quest_part1")
       --db.actor:disable_info_portion ("mil_courier_quest_part2")
       --db.actor:disable_info_portion ("mil_courier_in_khutor_zone")
       --db.actor:disable_info_portion ("mil_actor_in_khutor_zone_inside")
       --db.actor:disable_info_portion ("mil_courier_khutor_leave")
       --level_tasks.remove_location (710, "mil_courier_location")
       --level_tasks.add_location (707, "mil_lukash_location")
       --return
    --end   
end


function set_cook_mapspot ()
   level_tasks.add_location (728, "mil_cook_location")
end

function set_lukash_mapspot ()
    level_tasks.add_location (707, "mil_lukash_location")
end

function remove_lukash_map_spot (actor, npc)
    if db.actor:has_info ("mil_lukash_map_spot") then
       level_tasks.remove_location (707, "mil_lukash_location")
       db.actor:disable_info_portion ("mil_lukash_map_spot")
    end   
end