module("garbage_monster_attack")

local zone_name = "mil_base_attack"

local monster1 =
		{
			"mil_flesh_scr_1", "mil_flesh_scr_2",
			"mil_flesh_scr_3", "mil_flesh_scr_4",
			"mil_flesh_scr_5", "mil_flesh_scr_6",
			"mil_flesh_scr_7", "mil_flesh_scr_8",
			"mil_flesh_scr_9", "mil_flesh_scr_10"
		}		

local monster2 =
		{
			"mil_boar_scr_1", "mil_boar_scr_2",
			"mil_boar_scr_3", "mil_boar_scr_4",
			"mil_boar_scr_5", "mil_boar_scr_6",
			"mil_boar_scr_7", "mil_boar_scr_8"
		}		

local monster3 =
		{
			"mil_pd_scr_1", "mil_pd_scr_2",
			"mil_pd_scr_3", "mil_pd_scr_4"
		}		

local monster4 =
		{
			"mil_controller_1"
		}		

local ways =
		{
			"mil_base_atc_path_1", "mil_base_atc_path_2",
			"mil_base_atc_path_3", "mil_base_atc_path_4",
			"mil_base_atc_path_5", "mil_base_atc_path_6",
			"mil_base_atc_path_7", "mil_base_atc_path_8",
			"mil_base_atc_path_9", "mil_base_atc_path_10",
			"mil_controler_path"
		}
		
local g_monsters1 	= {monster1, monster2, monster3, monster4 }
local g_monster_id1	= {}

function main()
	
	while(level.object(zone_name) == nil) do
		printf("wait script_zone")
		wait()
	end
	
	printf("___start millitary_monster_attack")

	while(garbage_monster_attack.monster_on_line(g_monsters1, g_monster_id1) == false) do
		printf("wait monster...")
		wait()
	end
	
	printf("___start print")
	local MilitaryTroop = garbage_monster_attack.GarbageRaidManager(ways, g_monster_id1, zone_name, zone_name)
	
	MilitaryTroop:Initialize()
	printf("___initialize()")
	while(true) do
		MilitaryTroop:Update()
		wait()
	end
end
