function main ()

    local niva = get_level_object ("niva")

    niva:script (true, military4.script_name ())

	action (niva, object ("left_light", object.activate), cond (cond.time_end, 1000))
	action (niva, object ("right_light", object.activate), cond (cond.time_end, 1000))

    wait (30000)

    action (niva, move (move.on + move.up + move.fwd, 20.1), object ("right_light", object.activate),
            object ("left_light", object.activate), cond (cond.time_end, 8200))
    action (niva, move (move.right + move.on + move.fwd, 20.1), cond (cond.time_end, 655))
    action (niva, move (move.on + move.up + move.fwd, 20.1), cond (cond.time_end, 14750))

    while niva:action () do wait () end

    reset_action (niva, military4.script_name ())


    action (niva, move (move.off, 0), cond (cond.time_end, 2000))
    action (niva, object ("left_door", object.activate), cond (cond.time_end, time_infinite))

	while niva:action () do wait () end

    niva:script (false, military4.script_name ())

end
