function main()
	wait(10000)                                                                                                    
	                                                                                                              
	flesh  	= 	get_level_object("m_flesh_e0000")                                                                     
	actor   = 	get_actor()

	flesh:script(true,monster.script_name())                                                                                

	action(                                                                                                       
    	flesh,                                                                                                      
		move(move.act_eat,actor),
    	cond(cond.time_end,30000) 
	)                                                                                                             

	action(
		flesh,
		move(move.act_walk_fwd, actor),
	    cond(cond.time_end,3000)                                                                                 
	)	                                               	

	while flesh:action() do                                                        
	    wait			()                                                                                                    
	end                                                                                                           
	                                                                                                              
	flesh:script(false,monster.script_name()) 
end
