--------------------------------------------------------------------------------
-- Author:	Jim 
-- Desc:	script for monster tests
-- Updated:	21 dec 2004	
--------------------------------------------------------------------------------

function set_action(obj)
	action (obj, look(patrol("way"):point(0), 0.6, 0.6), cond (cond.look_end))
	action (obj, look(patrol("way"):point(1), 0.6, 0.6), cond (cond.look_end)) 
	action (obj, look(level.actor():position(), 0.6, 0.6), cond (cond.look_end)) 
end



function main()
	local obj			= get_level_object("searcher")

	obj:script			( true, script_name() )
	
	while true do
		
		set_action(obj)

		while obj:action() do 
			wait() 
		end
			
	end

	obj:script( false, script_name() )
end
