function main ()

    local stalker_guard4 = get_level_object ("stalker_guard4")

    stalker_guard4:script (true, move1_4.script_name())

    action (stalker_guard4, 
			move (move.standing, move.stand, move.line, patrol ("guard_way1")),
      		look (look.search), 
			anim (anim.free), 
			cond (cond.time_end, 1000000))

    while stalker_guard4:action () do wait () end

    stalker_guard4:script (false, move1_4.script_name())

end
