function main ()

    local stalker_guard3 = get_level_object ("stalker_guard3")

    stalker_guard3:script (true, move1_2.script_name())

    action (stalker_guard3, 
			move (move.standing, move.walk, move.line, patrol ("guard_way3")),
      		look (look.search), 
			anim (anim.free), 
			cond (cond.time_end, 1000000))

    while stalker_guard3:action () do wait () end

    stalker_guard3:script (false, move1_2.script_name())

end
