----------------------------------------------------------------------------------------------------
-- Physic gate control
----------------------------------------------------------------------------------------------------
-- »сходный скрипт (ph_door): Evgeniy Negrobov (Jon) jon@gsc-game.kiev.ua
-- ƒоработка: Oleg Kreptul (Haron) haronk@ukr.net
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
--[[
—осто€ни€:
state: состо€ние, в котором дверь находитс€ при инициализации
    opened - в открытом
    closed - в закрытом
    none - в текущем (дефолтном)
locking: блокировка дверей
    stick - прилипание дверей к крайним состо€ни€м
    soft - дверь заблокирована с помощью силы, т.е. можно ее открыть/пробить машиной
        state:
            opened - блокировать в открытом состо€нии
            closed - в закрытом
            none - не используетс€ (м€гка€ блокировка возможна только в крайних положени€х)
    hard - блокировка двери с помощью границ. ¬орота можно только сломать.
        state:
            opened - блокировать в открытом состо€нии
            closed - в закрытом
            none - в текущем
    none - дверь не заблокирована
--]]

local state_none = 0

local state_opened = 1
local state_closed = 2

local state_lock_stick = 1
local state_lock_soft = 2
local state_lock_hard = 3
----------------------------------------------------------------------------------------------------

local def_min_limit = -100.0 * math.pi / 180.0
local def_max_limit = 0.0
local def_close_angle = 0.0
local def_max_close_angle_diff = 10 * math.pi / 180.0
local def_stick_angle = 5 * math.pi / 180.0

local def_open_force = 200
local def_open_velocity = 3

local def_close_force = 200
local def_close_velocity = 3

local def_stick_force = 100
local def_stick_velocity = 1

local def_soft_lock_force = 30000
local def_soft_lock_velocity = 5

class "action_gate"

function action_gate:__init(obj, storage)
	printf	("action_gate::action_gate() called")
	self.object = obj
	self.st = storage
	self.snd_obj = nil
end

function action_gate:__finalize()
	printf	("action_gate::~action_gate() called")
end

function action_gate:reset_scheme(loading)
	printf("_bp: action_gate:reset_scheme: self.object:name()='%s'", self.object:name())
	self.initialized = false
	
	self:initialize(loading)
end

function action_gate:initialize(loading)
	local ph_shell = self.object:get_physics_shell()
	if not ph_shell then
		return
	end
	
	if self.st.tip_open then
		self.tip_open = string_table():get_by_id(self.st.tip_open)
	else
		self.tip_open = nil
	end
	if self.st.tip_close then
		self.tip_close = string_table():get_by_id(self.st.tip_close)
	else
		self.tip_close = nil
	end

	self.joint_left = ph_shell:get_joint_by_bone_name("door_left")
	self.joint_right = ph_shell:get_joint_by_bone_name("door_right")
	
	local angle_left = self.joint_left:get_axis_angle(1)
	local angle_right = self.joint_right:get_axis_angle(1)
	printf("_bp: gate def angles. left(%f) right(%f)", angle_left, angle_right)

	local disable_snd
	-- «вук нужно отключить, только если скрипт двери дл€ этого объекта используетс€
	-- впервые (т.е. после загрузки уровн€ или после загрузки сохраненной игры),
	-- иначе игрок услышит хлопок...
	if not self.st.script_used_more_than_once then
		disable_snd = true
		self.st.script_used_more_than_once = true
	end

	if self.st.state == "opened" then
	    printf("_bp: ph_gate.state = opened")
	    self.state = state_opened
		--self:open_gate(disable_snd)
	elseif self.st.state == "closed" then
	    printf("_bp: ph_gate.state = closed")
	    self.state = state_closed
		--self:close_gate(disable_snd)
	else
	    printf("_bp: ph_gate.state = none")
	    self.state = state_none
	end
	
	if self.st.locking == "stick" then
	    printf("_bp: ph_gate.locking = stick")
	    self.locking = state_lock_stick
	    if self.state == state_opened then
	        self.left_stick_dir = 1
	        self.right_stick_dir = 1
	    elseif self.state == state_closed then
	        self.left_stick_dir = -1
	        self.right_stick_dir = -1
	    else
	        self.left_stick_dir = 0
	        self.right_stick_dir = 0
	    end
	elseif self.st.locking == "soft" then
	    printf("_bp: ph_gate.locking = soft")
	    local angle_left, angle_right, force, velocity

	    self.locking = state_lock_soft
	    if self.state == state_opened then
	        force = def_soft_lock_force
	        velocity = -def_soft_lock_velocity
	    elseif self.state == state_closed then
	        force = def_soft_lock_force
	        velocity = def_soft_lock_velocity
	    else
	        force = 0
	        velocity = 0
	    end
	    self.joint_left:set_max_force_and_velocity(force, velocity, 1)
	    self.joint_right:set_max_force_and_velocity(force, velocity, 1)

	    if self.tip_open then
		    self.object:set_tip_text(self.tip_open)
	    end
	elseif self.st.locking == "hard" then
	    printf("_bp: ph_gate.locking = hard")
	    local angle_left
	    local angle_right

	    self.locking = state_lock_hard
	    if self.state == state_opened then
	        angle_left = def_max_limit
	        angle_right = def_max_limit
	    elseif self.state == state_closed then
	        angle_left = def_min_limit
	        angle_right = def_min_limit
	    else
	        angle_left = self.joint_left:get_axis_angle(1)
	        angle_right = self.joint_right:get_axis_angle(1)
	    end
	    self.joint_left:set_limits(angle_left, angle_left, 1)
	    self.joint_right:set_limits(angle_right, angle_right, 1)

	    if self.tip_open then
		    self.object:set_tip_text(self.tip_open)
	    end
	else
	    printf("_bp: ph_gate.locking = none")
	    self.locking = state_none
	    if self.state == state_opened then
		    self:open_gate(disable_snd)
	    elseif self.state == state_closed then
		    self:close_gate(disable_snd)
	    end
	end
	
	--self.joint_left:set_limits(def_min_limit, def_max_limit, 1)
	--self.joint_right:set_limits(def_min_limit, def_max_limit, 1)

	self.left_low_limits, self.left_hi_limits = 0, 0
	self.left_low_limits, self.left_hi_limits	= self.joint_left:get_limits(self.left_low_limits, self.left_hi_limits, 0)
	printf("_bp: left_limits(%f,%f)", self.left_low_limits, self.left_hi_limits)

	self.right_low_limits, self.right_hi_limits = 0, 0
	self.right_low_limits, self.right_hi_limits	= self.joint_right:get_limits(self.right_low_limits, self.right_hi_limits, 0)
	printf("_bp: right_limits(%f,%f)", self.right_low_limits, self.right_hi_limits)

	--self.block = false
	self.soundless_block = false

	self.object:set_nonscript_usable(false)
	-- FIXME: перевести под универсальную схему
	self.object:set_callback(callback.use_object, self.use_callback, self)
	self.object:set_callback(callback.hit, self.hit_callback, self)

	if self.st.snd_init then
		self:gate_play_snd_from_set(self.st.snd_init)
	end
	
	self.initialized = true
end

function action_gate:gate_play_snd_from_set(sndset)
	local snd = mob_sound.pick_sound_from_set(self.object, sndset, {})
	if not snd then
		utils.abort("physic object '%s': section '%s': sound set '%s' does not exist",
			self.object:name(), self.st.section, sndset)
	end
	
	self.snd_obj = sound_object(snd)
	if not self.snd_obj then
		utils.abort("object '%s': unable to create a sound object for sound '%s' (soundset '%s')",
			self.object:name(), snd, sndset)
	end
	self.snd_obj:play_at_pos(self.object, self.object:position())--, 0, sound_object.s2d) -- FIXME: don't use position()
end

function action_gate:update(delta)
	--printf("_bp: action_gate:update()", delta)

	if not self.initialized then
		utils.abort("object '%s': gate failed to initialize", self.object:name())
	end

	local actor = db.actor

	if xr_logic.try_switch_to_another_section(self.object, self.st, actor) then
		return
	end
end

--[[
function action_gate:fastcall()
	if self:close_check() then
		self:close_action()
		printf("_bp: action_gate: fastcall(): return true")
		return true
	end
	printf("_bp: action_gate: fastcall(): return false")
	return false
end

function action_gate:close_check()
	printf("_bp: close_check(): %d", time_global())
	if not self.initialized then
		printf("_bp: close_check(): not initialized")
		return false
	end

	--if self.block then
	if self.st.locked then
		return self:is_closed()
	end
	printf("_bp: close_check(): false")
	return false
end

function action_gate:close_action()
	--printf("_bp: close_action(): %d", time_global())

	printf("_bp: action_gate:update(): gate blocked")
	-- «акрыли до предела, будем блокировать
	--self.joint_left:set_max_force_and_velocity(10000, -1, 1)
	--self.joint_right:set_max_force_and_velocity(10000, -1, 1)
	self.joint_left:set_max_force_and_velocity(def_close_force, def_close_velocity, 1)
	self.joint_right:set_max_force_and_velocity(def_close_force, def_close_velocity, 1)
	--self.block = false
	-- ќтыграть звук когда дверь захлопнулась:
	if not self.soundless_block and self.st.snd_close_stop then
		self:gate_play_snd_from_set(self.st.snd_close_stop)
	end
end
--]]

function action_gate:open_gate(disable_snd)
	printf("_bp: action_gate:open_gate()")
	if not disable_snd then
		if self.st.snd_open_start then
			self:gate_play_snd_from_set(self.st.snd_open_start)
		end
	end
	
	--self.joint_left:set_max_force_and_velocity(200, 3, 0)
	--self.joint_right:set_max_force_and_velocity(200, 3, 0)
	self.joint_left:set_max_force_and_velocity(def_open_force, -def_open_velocity, 1)
	self.joint_right:set_max_force_and_velocity(def_open_force, -def_open_velocity, 1)
	self.state = state_opened
	--self.block = false

	if self.tip_close then
		self.object:set_tip_text(self.tip_close)
	end
end

function action_gate:is_closed()
	local angle_left = self.joint_left:get_axis_angle(1)
	local angle_right = self.joint_right:get_axis_angle(1)
	printf("_bp: action_gate:update(): left: angle %f limits %f, %f; right: angle %f limits %f, %f",
		angle_left, self.left_low_limits, self.left_hi_limits,
		angle_right, self.right_low_limits, self.right_hi_limits)
	if angle_left <= self.left_low_limits and angle_right <= self.right_low_limits then
		printf("_bp: close_check(): true")
		return true
	end
end

function action_gate:close_gate(disable_snd)
	--local disable_snd = self:is_closed()
	if not disable_snd then
		if self.st.snd_close_start then
			self:gate_play_snd_from_set(self.st.snd_close_start)
		end
	end

	-- —тавим коллбек дл€ отлова окончани€ закрыти€ двери (чтобы заблокировать ее и проиграть звук, если нужно):
	--printf("_bp: action_gate: setting physics callback from close_gate")
	--self.object:set_fastcall(self.fastcall,self)
	--self.object:set_fastcall(self.fastcall,self)
	--self.object:set_fastcall(self.fastcall,self)

	printf("_bp: action_gate:close_gate()")
	--self.joint_left:set_max_force_and_velocity(200, 3, 1)
	--self.joint_right:set_max_force_and_velocity(200, 3, 1)
	self.joint_left:set_max_force_and_velocity(def_close_force, def_close_velocity, 1)
	self.joint_right:set_max_force_and_velocity(def_close_force, def_close_velocity, 1)
	--self.block = true -- «акрываем и блокируем	
	self.soundless_block = disable_snd
	self.state = state_closed

	if self.tip_open then
		self.object:set_tip_text(self.tip_open)
	end
end

function action_gate:try_switch()
	printf("_bp: action_gate: object '%s': try_switch", self.object:name())
	local st = db.storage[self.object:id()]
	if st.active_scheme and st.active_scheme == "ph_gate" and self.st.on_use then
		--if xr_logic.try_switch_to_another_section(obj, self.st, db.actor) then
		if xr_logic.switch_to_section(self.object, self.st,
		   xr_logic.pick_section_from_condlist(db.actor, self.object, self.st.on_use.condlist)) then
			return true
		end
	end
	return false
end

-- 
function action_gate:hit_callback(obj, amount, local_direction, who, bone_index)
    printf("_bp: action_gate:hit_callback()")
	if self.locking == state_lock_hard or self.locking == state_lock_soft then
		if self.st.snd_open_start then
			self:gate_play_snd_from_set(self.st.snd_open_start)
		end
		return
	end
--[[
	if self.locking == state_lock_stick then
	    self.left_stick_dir, self.right_stick_dir = self:get_stickness()
	    if 
	    self.joint_left:set_max_force_and_velocity(def_close_force, def_close_velocity, 1)
	    self.joint_right:set_max_force_and_velocity(def_close_force, def_close_velocity, 1)
	    --if s ~= 0 then
	    --end
	end
--]]
end

function action_gate:use_callback(obj, who)
    printf("_bp: action_gate:use_callback()")
	if self:try_switch() then
		return
	end
	
	if self.locking == state_lock_hard or self.locking == state_lock_soft then
		if self.st.snd_open_start then
			self:gate_play_snd_from_set(self.st.snd_open_start)
		end
		return
	end

	if self.st.locked then
		if self.st.snd_open_start then
			self:gate_play_snd_from_set(self.st.snd_open_start)
		end
		return
	end

	local angle_left = self.joint_left:get_axis_angle(1)
	local angle_right = self.joint_right:get_axis_angle(1)

	--if angle_left - self.left_low_limits < self.left_hi_limits - angle_left and
	--   angle_right - self.right_low_limits < self.right_hi_limits - angle_right then
	if angle_left < def_close_angle - def_max_close_angle_diff or
	   angle_right < def_close_angle - def_max_close_angle_diff then
		self:close_gate(false)
	else
		self:open_gate(false)
	end
end

---------------------------------------------------------------------------------------------------------------------
function add_to_binder(npc, ini, scheme, section, storage)
	printf("DEBUG: add_to_binder: scheme='%s', section='%s'", scheme, section)

	local new_action = action_gate(npc, storage)

	-- «арегистрировать все actions, в которых должен быть вызван метод reset_scheme при изменении настроек схемы:
	xr_logic.subscribe_action_for_events(npc, storage, new_action)
end

function set_scheme(npc, ini, scheme, section, gulag_name)
	local st = xr_logic.assign_storage_and_bind(npc, ini, scheme, section)

	st.logic     = xr_logic.cfg_get_switch_conditions(ini, section, npc)

	st.state     = utils.cfg_get_string(ini, section, "state", npc, false, "", "none")
	st.locking   = utils.cfg_get_string(ini, section, "locking", npc, false, "", "none")

	--st.closed    = utils.cfg_get_bool(ini, section, "closed", npc, false, true)
	--st.locked    = utils.cfg_get_bool(ini, section, "locked", npc, false)
	if not st.locked then
		st.tip_open  = utils.cfg_get_string(ini, section, "tip_open", npc, false, "", "tip_gate_open")
		st.tip_close = utils.cfg_get_string(ini, section, "tip_close", npc, false, "", "tip_gate_close")
	else
		st.tip_open  = utils.cfg_get_string(ini, section, "tip_open", npc, false, "", "tip_gate_locked")
	end
	st.snd_init        = utils.cfg_get_string(ini, section, "snd_init", npc, false, "")
	st.snd_open_start  = utils.cfg_get_string(ini, section, "snd_open_start", npc, false, "")
	st.snd_close_start = utils.cfg_get_string(ini, section, "snd_close_start", npc, false, "")
	st.snd_close_stop  = utils.cfg_get_string(ini, section, "snd_close_stop", npc, false, "")
	
	st.on_use    = xr_logic.cfg_get_condlist(ini, section, "on_use", npc)
end

function disable_scheme(npc, scheme)
	local st = db.storage[npc:id()][scheme]
	if st then
		xr_logic.unsubscribe_action_from_events(npc, st, st.action)
	end
end
