function main ()

    local stalker = get_level_object ("muzhik")
    local kaban = get_level_object ("kaban")
    
    stalker:script (true, s_test.script_name ())
    action (stalker, look (look.search), anim (anim.free), cond (cond.time_end, time_infinite))
    
    local obj = kaban:best_enemy ()
    
    if obj ~= nil then printf ("Enemy name %s", obj:name ()) end
    while true do wait () end
    
end