function test_print (str)
	printf ("This is test %d", str)
end

function main ()


	s_test.test_print (566)

	local stalker = get_level_object ("m_stalker_e0000")
	stalker:script (true, s_test.script_name ())
	local torch = get_level_object ("torch")
	if (torch ~= nil) then printf ("Getting torch") flush () end

	action (stalker, move (move.standing, move.walk, move.line, patrol ("way0000")),
			look (look.search), anim (anim.free), object (torch, object.activate), 
			cond (cond.time_end, 1000000000000))

	while stalker:action () do 
		  if stalker:alive () == false then break end
		  wait () 
		  end

	stalker:script (false, s_test.script_name ())
	
 end