-- define class const evaluator
class "const_evaluator"		(property_evaluator)

function const_evaluator:__init(value) super()
	self.value				= value
end

function const_evaluator:evaluate()
	return					self.value
end

-- define class custom action
class "custom_action"		(action_base)

function custom_action:__init(weight,object,name) super(object,name)
	self.m_weight			= weight
	self.name				= name
end

function custom_action:weight(world_state0,world_state1)
	return					self.m_weight
end

--function custom_action:initialize()
--	action_base.initialize	(self)
--end

--function custom_action:execute()
--	action_base.execute		(self)
--	printf					("action %s is executed!",self.name)
--end

function custom_action:finalize()
	action_base.finalize	(self)
end

class "custom_planner" 		(action_planner)

function custom_planner:__init	() super()
end

function custom_planner:reinit	(obj, clear_all)
	action_planner.reinit	(self, obj, clear_all)
end

function main()
	-- define world properties
	local property_id0		= 0
	local property_id1		= 1
	local property_id2		= 2
	local property_id3		= 3
	
	-- define action identifiers
	local action_id0		= 0
	local action_id1		= 1
	local action_id2		= 2
	local action_id3		= 3

	-- define evaluators
	local eval0				= stalker_test.const_evaluator(false)
	local eval1				= stalker_test.const_evaluator(false)
	local eval2				= stalker_test.const_evaluator(false)
	local eval3				= stalker_test.const_evaluator(false)
	
	-- define actions
	local action0			= stalker_test.custom_action(1,nil,"action0")
	local action1			= stalker_test.custom_action(1,nil,"action1")
	local action2			= stalker_test.custom_action(1,nil,"action2")
	local action3			= stalker_test.custom_action(1,nil,"action3")
	
	-- define action conditions and effects
	action0:add_precondition(world_property(property_id0,false))
	action0:add_effect		(world_property(property_id0,true))
	
	action1:add_precondition(world_property(property_id1,false))
	action1:add_effect		(world_property(property_id1,true))
	
	action2:add_precondition(world_property(property_id2,false))
	action2:add_effect		(world_property(property_id2,true))
	
	action3:add_precondition(world_property(property_id3,false))
	action3:add_effect		(world_property(property_id3,true))
	
	-- define planner
	local planner			= stalker_test.custom_planner()
	planner:reinit			(get_actor(),false)
	
	-- add evaluators
	planner:add_evaluator	(property_id0,eval0)
	planner:add_evaluator	(property_id1,eval1)
	planner:add_evaluator	(property_id2,eval2)
	planner:add_evaluator	(property_id3,eval3)
	
	-- add actions
	planner:add_action		(action_id0,action0)
	planner:add_action		(action_id1,action1)
	planner:add_action		(action_id2,action2)
	planner:add_action		(action_id3,action3)
	
	-- define goal
	local 					goal = world_state()			
	goal:add_property		(world_property(property_id0,true))
	goal:add_property		(world_property(property_id1,true))
	goal:add_property		(world_property(property_id2,true))
	goal:add_property		(world_property(property_id3,true))
	
	-- setup goal
	planner:set_goal_world_state(goal)
	
	-- update cycle
	while true do
		planner:update		(1000)
		wait				(1000)
	end
	
	-- the end
end