function main()
    actor				= get_actor()
    stalker				= get_level_object ("m_stalker_e0000")
    
    stalker:script		(true,stalker_test:script_name());
    
--[
    action				(
		stalker,
		look			(look.fire_point,actor),
		anim			(anim.danger),
		move			(move.standing,move.walk,move.line,actor),
		cond			(cond.time_end,10000)
    )
--]
    
    action				(
		stalker,
		look			(look.fire_point,actor),
		anim			(anim.danger),
		move			(move.standing,move.walk,move.line,patrol("way0000")),
		cond			(cond.time_end,10000)
    )
    
	while stalker:action() do
		printf			("%s",stalker:best_weapon():name())
		wait			()
    end
    
    action				(
		stalker,
		look			(look.fire_point,actor),
		anim			(anim.danger),
		move			(move.standing,move.walk,move.line,patrol("way0001")),
		cond			(cond.move_end)
    )
    
	while stalker:action() do
		printf			("%s",stalker:best_weapon():name())
		wait			()
    end
    
    stalker:script		(false,stalker_test:script_name());
end