module("ui_save_dialog")
module("ui_load_dialog")

function dump_time(t)
printf("----dump time start")
/*	printf(t:dateToString(game.time_struct.DateToDay))
	printf(t:dateToString(game.time_struct.DateToMonth))
	printf(t:dateToString(game.time_struct.DateToYear))
	
	printf(t:timeToString(game.time_struct.TimeToHours))
	printf(t:timeToString(game.time_struct.TimeToMinutes))
	printf(t:timeToString(game.time_struct.TimeToSeconds))
*/	
	printf(t:timeToString(game.time_struct.TimeToMilisecs))
printf("----dump time end")
printf("")
end

function main()
--local dlg = ui_main_menu.main_menu()
--level.start_stop_menu(dlg,true)
--	while (1) do
	--	wait(1000)
	--end
	local t = game.time2()
	dump_time(t)
	local dt = game.time_struct()
	dt:setHMSms(3,4,5,67)
	dump_time(dt)
	t = t+dt
	dump_time(t)
	
end
