
class "HeliManager";
function HeliManager:__init()
end

function HeliManager:__finalize()
end


function HeliManager:Init()
   self.m_heli = get_level_object( "helicopter" )
   self.m_heli:AddEventCallback(1,self,"onHeliEvent")
end

function HeliManager:onHeliEvent(p)
		local str = p:r_stringZ()
      printf(str)
      local player = get_actor()
      
      self.m_heli:heli_go_to_point(player:position(),player:position(),6)
end

function HeliManager:Start()
	while true do

   wait()
   end
end


function main()

local heli_mngr = HeliManager()
heli_mngr:Init()
heli_mngr:Start()

--		heli:heli_go_by_patrol_path( "heli_way_1" )
end
