

function dump_time(t)
/*	printf(t:dateToString(game.CTime.DateToDay))
	printf(t:dateToString(game.CTime.DateToMonth))
	printf(t:dateToString(game.CTime.DateToYear))
	
	printf(t:timeToString(game.CTime.TimeToHours))
	printf(t:timeToString(game.CTime.TimeToMinutes))
	printf(t:timeToString(game.CTime.TimeToSeconds))
*/	
	printf(t:timeToString(game.CTime.TimeToMilisecs))
	printf("")
end


function main_()
	
	local dt = game.get_game_time()
	dump_time(dt)
	
	local dt2 = game.CTime()
	dt2:setHMS(2,3,4)
	dump_time(dt2)
	dump_time(dt)
	local s  = dt2:diffSec(dt)
	
	if dt>dt2 then
		printf("dt>dt2")
	end

	if dt>=dt2 then
		printf("dt>=dt2")
	end

	if dt<dt2 then
		printf("dt<dt2")
	end

	if dt<=dt2 then
		printf("dt<=dt2")
	end

	if dt==dt2 then
		printf("dt==dt2")
	end

end
