

function dump_time(t)
	printf(t:dateToString(game.CTime.DateToDay))
	printf(t:timeToString(game.CTime.TimeToMilisecs))
	printf("")
end


function main()
	
	local dt = game.get_game_time()
	dump_time(dt)
	
	local dt2 = game.CTime()
	dt2:setHMS(2,3,4)
	
	local dt3 = game.CTime()
	dt3:setHMS(2,5,4)

	local s  = dt2:diffSec(dt3)
	printf("---difference = %f",s)
	
	
	if dt>dt2 then
		printf("dt>dt2")
	end

	if dt>=dt2 then
		printf("dt>=dt2")
	end

	if dt<dt2 then
		printf("dt<dt2")
	end

	if dt<=dt2 then
		printf("dt<=dt2")
	end

	if dt==dt2 then
		printf("dt==dt2")
	end

end
