
local object_list		= {}
local smart_terrains	= {}
local object_id_list	= {}

------------------------------------------------------------------------------
-- Services
------------------------------------------------------------------------------

-- Save id of object while loading
function save_object_id()
	for test_name, test_name_table in pairs(object_list) do
		local tab = {}
		for index, obj_name in pairs(test_name_table) do
			local obj =	level.debug_object(tostring(obj_name))
			if (obj ~= nil) then
				table.insert(tab,tonumber(obj:id()))
			end
		end
		object_id_list[tostring(test_name)] = tab
	end
end


-- Check if object online
function object_online(object_id)
	return (alife() == nil) or alife():object(object_id).online
end

-- Move all offline
function offline_all()
	for test_name, test_name_table in pairs(object_list) do
		for index, obj_name in pairs(test_name_table) do
			local obj =	 level.debug_object(tostring(obj_name))
			if ((obj ~= nil) and (object_online(obj:id()))) then
				alife():set_switch_online	(obj:id(),false)
				alife():set_switch_offline	(obj:id(),true)
			end
		end
	end
end

-- except test name
function offline_all_except(except_name)
	for test_name, test_name_table in pairs(object_list) do
		if (except_name ~= test_name) then
			for index, obj_name in pairs(test_name_table) do
				local obj =	 level.debug_object(tostring(obj_name))
				if ((obj ~= nil) and (object_online(obj:id()))) then
					alife():set_switch_online	(obj:id(),false)
					alife():set_switch_offline	(obj:id(),true)
				end
			end
		end
	end
end



-- Move online objects that are in scene index 
function online_scene(index)
	local tab = object_id_list["test" .. tostring(index)];
	for index, obj_id in pairs(tab) do
		local obj =	alife():object(tonumber(obj_id))
		if (obj ~= nil) then
			alife():set_switch_online	(obj_id,true)
			alife():set_switch_offline	(obj_id,false)
		end
	end
end

-- gulag in test
function is_gulag_in_test(gulag_name, test_name)
	if smart_terrains[test_name] == nil then 
		return false 
	end
	for index, cur_gulag_name in smart_terrains[test_name] do
		if gulag_name == cur_gulag_name then
			return true
		end
	end
	return false
end


-- remove all gulags except test name
function remove_gulags_except(test_name)
	for k, v in db.smart_terrain_by_id do
		if (is_gulag_in_test(v:name(), test_name) == false) then
			smart_terrain.remove_gulag(v,true)
		end
	end
end


-- Debug info
function debug()
	for test_name, test_name_table in pairs(object_id_list) do
		printf(":: TEST : test [%s]", tostring(test_name))
		for index, obj_id in pairs(test_name_table) do
			printf(":: TEST : getting object [id=%u]", tonumber(obj_id))
			local obj =	alife():object(tonumber(obj_id))
			if (obj ~= nil) then
				printf(":: TEST : obj_name = [%s] id =[%u]",obj:name(), tonumber(obj_id))
			end
		end
	end
end



------------------------------------------------------------------------------
-- Base routines
------------------------------------------------------------------------------

function setup_test(obj_list, smart_terr_list)
	object_list		= obj_list
	smart_terrains	= smart_terr_list
end


function run_test(index)
	local test_name = "test" .. tostring(index)
	
--	-- not using smart terrains?
--	if smart_terrains == nil then
--		offline_all()
--		online_scene(index)
--	else -- using smart terrains
--		remove_gulags_except(test_name)	
--		offline_all_except(test_name)
--	end

	remove_gulags_except(test_name)	
	offline_all_except(test_name)
end

-- Execute Base
function run_global()
	wait_game(2000)
	save_object_id()
	offline_all()
end

