-- File:        UI_MAIN_BASE_TAB.SCRIPT
-- Description: base tab for some Main Menu dialogs (Main, New Game, Multiplayer)
-- Created:     16.12.2004
-- Author:      Serhiy 0. Vynnychenk0
-- Mail:        narrator@gsc-game.kiev.ua
--
-- Copyright 2004 GSC Game World
--

class "ui_main_base_tab" (CUIScriptWnd)

function ui_main_base_tab:__init() super()
end

function ui_main_base_tab:__finalize()
end

function ui_main_base_tab:InitControls()
end

