class "save_dialog" (CUIScriptWnd)

function save_dialog:__init() super()
   self:SetFont(GetFontMedium()) --set base font for dialog.
   
   self:InitControls()
   self:InitCallBacks()
end

function save_dialog:__finilize()

end

function save_dialog:InitControls()
	self:Init(100,100,257,271) --init self position and size
	
	local screen_height = 768
	local screen_width  = 1024
	

	------------LIST EXAMPLE-----------------

--------------------------------------- 
    local btn   = CUIButton()
	btn:SetAutoDelete(true) 
	btn:SetWindowName("button_ok") --set window name for callback processing
	
	btn:Init("ui\\ui_button_01",10,210,135,40)
--  btn:Init(10,10,100,100) --or without texture
    btn:SetText("OK")
	btn:SetTextAlign(CGameFont.alCenter) --horizontal align. possible values are [alCenter,alLeft,alRight]
	btn:SetTextY(20) --vertical align(pixel). set value to -1 for center
	self:Register(btn) --for event-handling
	txt_main:AttachChild(btn)
--------------------------------------
    btn   = CUIButton()
    btn:SetAutoDelete(true)
    btn:SetWindowName("button_cancel")
	
	btn:Init("ui\\ui_button_01",130,210,135,40) 	
	btn:SetText("cancel")
	btn:SetTextAlign(CGameFont.alCenter)
	btn:SetTextY(20)
	self:Register(btn)
	txt_main:AttachChild(btn)
end

function save_dialog:InitCallBacks()
	self:AddCallback("button_ok",ui_events.BUTTON_CLICKED,self,"OnButton_ok_clicked")
	self:AddCallback("button_cancel",ui_events.BUTTON_CLICKED,self,"OnButton_cancel_clicked")
end

function save_dialog:OnButton_ok_clicked()
	
end

function save_dialog:OnButton_cancel_clicked()
	

end
