
local leader_no_command          = 0
local leader_move                       = 1
local leader_stop                       = 2
local leader_speak            = 3
local leader_speak_enable        = 4
local leader_return                     = 5
local leader_free                       = 6


-------------------------------------------------------------------------
class "evaluator_chaser" (property_evaluator)
------------------
function evaluator_chaser:__init (storage, name) super ()
    self.a = storage
end
------------------
function evaluator_chaser:evaluate ()
    if self.a.npc == nil or self.a.npc:alive () == false then return false end
    return true
end
-------------------------------------------------------------------------


-------------------------------------------------------------------------
class "evaluator_chaser_enable" (property_evaluator)
------------------
function evaluator_chaser_enable:__init (storage, name) super ()
    self.a = storage
end
------------------
function evaluator_chaser_enable:evaluate ()
    return self.a.enabled == true
end
-------------------------------------------------------------------------


-------------------------------------------------------------------------
class "evaluator_return" (property_evaluator)
------------------
function evaluator_return:__init (storage, name) super ()
    self.a = storage
end
------------------
function evaluator_return:evaluator ()
    printf ("Level vertex id = %d, object vertex id = %d", self.a.ret_vertex, self.object:level_vertex_id ())
    if self.a.ret_vertex == -1 or self.object:level_vertex_id () == self.a.ret_vertex then
       return true
    end
    return false
end
-------------------------------------------------------------------------


-------------------------------------------------------------------------
class "action_chase" (action_base)
------------------
function action_chase:__init (storage, name) super (nil, name)
    self.a = storage
end
------------------
function action_chase:initialize ()
    action_base.initialize (self)
    self.object:clear_animations ()
    self.object:set_node_evaluator        ()
    self.object:set_path_evaluator        ()
    self.object:set_desired_position      ()
    self.object:set_item                  (object.idle, self.object:best_weapon ())
    self.object:set_detail_path_type      (move.line)
    self.object:set_body_state            (move.standing)
    self.object:set_movement_type         (move.run)
    self.object:set_mental_state          (anim.danger)
    self.object:set_path_type             (game_object.level_path)
    self.object:set_dest_level_vertex_id  (self.a.npc:level_vertex_id ())
    self.object:set_mental_state          (anim.free)
    self.object:set_sight                 (look.path_dir, nil, 0)
end
------------------
function action_chase:execute ()
    action_base.execute (self)
    self.object:set_path_type             (game_object.level_path)
    self.object:set_dest_level_vertex_id  (self.a.npc:level_vertex_id ())
    self.object:set_movement_type         (move.run)
    self.object:set_mental_state          (anim.danger)
    self:set_soldier_positions ()
    self:set_command (leader_move)
end
------------------
function action_chase:finalize ()
    action_base.finalize (self)
end
-------------------------------------------------------------------------
function action_chase:set_soldier_positions ()
    local size = table.getn (xr_motivator.storage[self.object:id()].followers)
    if size == 0 then return end
    local dir = self.object:direction ()
    dir.y = 0.0
    dir:normalize ()
    local step = 180.0 / size
    local angle = 90.0
    for a = 1, size, 1 do
        local vec
        if a == 1 then
           vec = vector_rotate_y (dir, 90.0)
        else
           vec = vector_rotate_y (dir, -90.0)
        end
        xr_motivator.storage[self.object:id()].followers[a].direction = vec
        xr_motivator.storage[self.object:id()].followers[a].distance = 3.0
    end
end
-------------------------------------------------------------------------
function action_chase:set_command (command)
    local size = table.getn (xr_motivator.storage[self.object:id()].followers)
    if size == 0 then return end
    for a = 1, size, 1 do
        xr_motivator.storage[self.object:id()].followers[a].leader_command = command
    end
end

-------------------------------------------------------------------------
class "action_return" (action_base)
------------------
function action_return:__init (storage, name) super (nil, name)
    self.a = storage
end
------------------
function action_return:initialize ()
    action_base.initialize (self)
    self.object:clear_animations          ()
    self.object:set_node_evaluator        ()
    self.object:set_path_evaluator        ()
    self.object:set_desired_position      ()
    self.object:set_item                  (object.idle, self.object:best_weapon ())
    self.object:set_detail_path_type      (move.line)
    self.object:set_body_state            (move.standing)
    self.object:set_movement_type         (move.run)
    self.object:set_mental_state          (anim.danger)
    self.object:set_path_type             (game_object.level_path)
    if self.a.ret_vertex == -1 then
       self.a.ret_vertex = self.object:level_vertex_id ()
       self.a.enabled = false
    end
    self.object:set_dest_level_vertex_id  (self.a.ret_vertex)
    self.object:set_mental_state          (anim.free)
    self.object:set_sight                 (look.path_dir, nil, 0)
end
------------------
function action_return:execute ()
    action_base.execute (self)
    self.object:set_path_type             (game_object.level_path)
    self.object:set_dest_level_vertex_id  (self.a.ret_vertex)
    self.object:set_movement_type         (move.run)
    self.object:set_mental_state          (anim.danger)
    self:set_soldier_positions ()
    self:set_command ()
end
------------------
function action_return:finalize ()
    action_base.finalize (self)
end
-------------------------------------------------------------------------
function action_return:set_soldier_positions ()
    local size = table.getn (xr_motivator.storage[self.object:id()].followers)
    if size == 0 then return end
    local dir = self.object:direction ()
    dir.y = 0.0
    dir:normalize ()
    local step = 180.0 / size
    local angle = 90.0
    for a = 1, size, 1 do
        local vec
        if a == 1 then
           vec = vector_rotate_y (dir, 90.0)
        else
           vec = vector_rotate_y (dir, -90.0)
        end
        xr_motivator.storage[self.object:id()].followers[a].direction = vec
        xr_motivator.storage[self.object:id()].followers[a].distance = 3.0
    end
end
-------------------------------------------------------------------------
function action_return:set_command (command)
    local size = table.getn (xr_motivator.storage[self.object:id()].followers)
    if size == 0 then return end
    for a = 1, size, 1 do
        xr_motivator.storage[self.object:id()].followers[a].leader_command = command
    end
end


-------------------------------------------------------------------------
function add_to_binder (npc, ini)
    local operators = {}
    local properties = {}

    properties["enabled"]           = xr_evaluators_id.sidor_chaser
    properties["chase"]             = xr_evaluators_id.sidor_chaser + 1
    properties["return"]            = xr_evaluators_id.sidor_chaser + 2
  properties["state_end"]        = xr_evaluators_id.state_change

    operators["chase"]              = xr_actions_id.sidor_act_chaser
    operators["return"]             = xr_actions_id.sidor_act_chaser + 1


    local manager = npc:motivation_action_manager ()
    manager:add_evaluator (properties["enabled"], this.evaluator_chaser_enable (xr_motivator.storage[npc:id ()].chaser, "evaluator_chaser_enabled"))
    manager:add_evaluator (properties["chase"], this.evaluator_chaser (xr_motivator.storage[npc:id ()].chaser, "evaluator_chaser"))
    manager:add_evaluator (properties["return"], this.evaluator_return (xr_motivator.storage[npc:id ()].chaser, "evaluator_return"))

    local action = this.action_chase (xr_motivator.storage[npc:id ()].chaser, "action_chase")
     action:add_precondition       (world_property (stalker_ids.property_alive,    true))
     action:add_precondition       (world_property (stalker_ids.property_enemy,    false))
     action:add_precondition       (world_property (properties["enabled"],         true))
     action:add_precondition       (world_property (properties["chase"],           true))
  action:add_precondition        (world_property (properties["state_end"],       true))
     action:add_effect             (world_property (properties["chase"],           false))
     manager:add_action              (operators["chase"], action)


    action = this.action_return (xr_motivator.storage[npc:id ()].chaser, "action_return")
     action:add_precondition       (world_property (stalker_ids.property_alive,    true))
     action:add_precondition       (world_property (stalker_ids.property_enemy,    false))
     action:add_precondition       (world_property (properties["enabled"],         true))
     action:add_precondition       (world_property (properties["chase"],           false))
     action:add_precondition       (world_property (properties["return"],          false))
  action:add_precondition        (world_property (properties["state_end"],       true))
     action:add_effect             (world_property (properties["enabled"],         false))
     manager:add_action              (operators["return"], action)

    action = manager:action (stalker_ids.action_puzzle_solver)
    action:add_precondition (world_property (properties["enabled"], false))

end
-------------------------------------------------------------------------
function set_chase (npc, enabled, sacrifice)
  local char_ini = npc:spawn_ini()
  local st = xr_motivator.storage[npc:id()].chaser

    if enabled == nil then
       if char_ini:section_exist ("chaser") == true and char_ini:line_exist("chaser", "enabled") == true then
          st.enabled = char_ini:r_bool("chaser", "enabled")
       else
          st.enabled = false
       end
    else
       st.enabled = enabled
    end

    if sacrifice == nil then
       st.enabled = false
    else
       st.npc = sacrifice
       st.ret_vertex = npc:level_vertex_id ()
    end

end
-------------------------------------------------------------------------
function clear_chase (npc)
    xr_motivator.storage[npc:id()].chaser.enabled = false
end