----------------------------------------------------------------------------------------------------------------------
--Actions
----------------------------------------------------------------------------------------------------------------------
-- Обычное поведение
class "action_process_death"
function action_process_death:__init(storage)
    self.a = storage
end
function action_process_death:death_callback(victim, who)
    if who ~= nil then
        printf("[%s] killed by [%s]", victim:name(), who:name() )
		xr_motivator.storage[victim:id()].death.killer = who:id()
    else
        printf("[%s] killed by [Unknown]", victim:name())
    end
	xr_logic.try_switch_to_another_section(victim, self.a)
end

----------------------------------------------------------------------------------------------------------------------
-- binder
----------------------------------------------------------------------------------------------------------------------
function add_to_binder(npc, ini, scheme, section, storage) 	
 	local action = this.action_process_death(storage)
	npc:set_death_callback(action, "death_callback")
end

function set_death_checker(npc, ini, scheme, section)
	local st = xr_logic.assign_storage_and_bind(npc, ini, scheme, section)
	st.logic     = xr_logic.cfg_get_switch_conditions(ini, section, npc)
end