----------------------------------------------------------------------------------------------------------------------
--	Схема изменений положения тела
--	автор: Диденко Руслан (Stohe)
--	TODO: 
----------------------------------------------------------------------------------------------------------------------

stand = 0
sit   = 2
sleep = 4

---------------------------------------------------------------------------------------------------------------------
--Evaluators
----------------------------------------------------------------------------------------------------------------------
-- Условие завершения скрипта
class "evaluator_state_end" (property_evaluator)
function evaluator_state_end:__init(storage) super()
	self.a = storage
end
function evaluator_state_end:evaluate()
	return self.a.body_state == self.a.target_state
end

-- стоим лимы
class "evaluator_standing" (property_evaluator)
function evaluator_standing:__init(storage) super()
	self.a = storage
end
function evaluator_standing:evaluate()
	return self.a.body_state == 0
end

----------------------------------------------------------------------------------------------------------------------
--Actions
----------------------------------------------------------------------------------------------------------------------
-- Изменяет положение тела
class "action_change_state" (action_base)
function action_change_state:__init (npc_name,action_name,storage) super (nil,action_name)
	self.a = storage
end
function action_change_state:initialize()
	action_base.initialize(self)
	self.object:set_node_evaluator()
	self.object:set_path_evaluator()
	self.object:set_desired_position()
	self.object:set_desired_direction()  

	self.object:clear_animations()

	if self.a.body_state == 0 then
		if self.a.target_state == 0 then
			--
		elseif self.a.target_state == 1 then
			self.object:add_animation("stalker_1_down", true)
		elseif self.a.target_state == 2 then
			self.object:add_animation("stalker_2_down", true)
		elseif self.a.target_state == 3 then
			self.object:add_animation("stalker_3_down", true)
		elseif self.a.target_state == 4 then
			self.object:add_animation("stalker_2_down", true)
			self.object:add_animation("spit_0", true)			
		end
	elseif self.a.body_state == 1 then
		if self.a.target_state == 0 then
			self.object:add_animation("stalker_1_up", true)
		elseif self.a.target_state == 1 then
			--
		elseif self.a.target_state == 2 then
			--!!!!
		elseif self.a.target_state == 3 then
			--!!!!
		elseif self.a.target_state == 4 then
			--!!!!
		end
	elseif self.a.body_state == 2 then
		if self.a.target_state == 0 then
			self.object:add_animation("stalker_2_up", true)
		elseif self.a.target_state == 1 then
			--!!!!
		elseif self.a.target_state == 2 then
			--
		elseif self.a.target_state == 3 then
			self.object:add_animation("stalker_2v3", true)
		elseif self.a.target_state == 4 then
			self.object:add_animation("spit_0", true)
		end
	elseif self.a.body_state == 3 then
		if self.a.target_state == 0 then
			self.object:add_animation("stalker_3_up", true)
		elseif self.a.target_state == 1 then
			--!!!!
		elseif self.a.target_state == 2 then
			self.object:add_animation("stalker_3v2", true)
		elseif self.a.target_state == 3 then
			--
		elseif self.a.target_state == 4 then
			--!!!!
		end
	elseif self.a.body_state == 4 then
		if self.a.target_state == 0 then
			self.object:add_animation("spit_3", true)
			self.object:add_animation("stalker_2_up", true)
		elseif self.a.target_state == 1 then
			--!!!!
		elseif self.a.target_state == 2 then
			self.object:add_animation("spit_3", true)
		elseif self.a.target_state == 3 then
			--!!!!
		elseif self.a.target_state == 4 then
			--
		end
	end
	a = xr_state.getIdle(self.a.target_state)
	if a ~= nil then
		self.object:add_animation(a, true)
	end

end
function action_change_state:execute ()
	if self.a.target_state == 0 then
		if self.object:animation_count() == 0 then
			self.a.body_state = self.a.target_state
		end
	else
		if self.object:animation_count() <= 1 then
			self.a.body_state = self.a.target_state
		end
	end

	action_base.execute (self)
end
function action_change_state:finalize ()
	action_base.finalize (self)
end

-- Вставание
class "action_stand_up" (action_base)
function action_stand_up:__init (npc_name,action_name,storage) super (nil,action_name)
	self.a = storage
end
function action_stand_up:initialize()
	action_base.initialize(self)
	self.object:set_node_evaluator()
	self.object:set_path_evaluator()
	self.object:set_desired_position()
	self.object:set_desired_direction()  
	xr_state.change_state(self.object, 0, true)
end
function action_stand_up:execute ()
	action_base.execute (self)
end
function action_stand_up:finalize ()
	action_base.finalize (self)
end

----------------------------------------------------------------------------------------------------------------------
-- Functions
----------------------------------------------------------------------------------------------------------------------
-- Проверка, изменилось ли уже положение тела или нет
function finish_state(object)
	local st = xr_motivator.storage[object:id()].state
	return st.body_state == st.target_state
end

--функция смены положения тела
function change_state(object, new, emerg)
	-- ОПИСАНИЕ ИДЕНТИФИКАТОРОВ ПОЗИЦИЙ:
	-- 0 - стоит                             
	-- 1 - сидит в положении для курения
	-- 2 - сидит в положении для водки
	-- 3 - сидит в положении для еды
	-- 4 - спит сидя
	local st = xr_motivator.storage[object:id()].state

	if new == st.target_state then
		return false
	end
	   	            
	if st.body_state ~= new then 
	      	st.target_state = new
		if emerg == true then
			st.body_state = st.target_state
		end

		return true
	else
		return false
	end
end
function getIdle(id)
	if id == 0 then
	elseif id == 1 then
		return "stalker_1_2"
	elseif id == 2 then
		return "stalker_2_1"
	elseif id == 3 then
		return "stalker_3_2"
	elseif id == 4 then
		return "spit_2"
	end
end

----------------------------------------------------------------------------------------------------------------------
--State binder
----------------------------------------------------------------------------------------------------------------------
function add_to_binder(object)
	local operators		= {}
	local properties	= {}

	properties["state_end"]		= xr_evaluators_id.state_change
	properties["stand"]		= xr_evaluators_id.stohe_state_base + 1

	operators["state"]		= xr_actions_id.stohe_state_base + 1
	operators["stand"]		= xr_actions_id.stohe_state_base + 2

	local manager = object:motivation_action_manager()
	-- Evaluators                                                                            
	manager:add_evaluator (properties["state_end"], 		this.evaluator_state_end		(xr_motivator.storage[object:id()].state))
	manager:add_evaluator (properties["stand"], 			this.evaluator_standing			(xr_motivator.storage[object:id()].state))

	-- Actions
	local action = this.action_change_state (object:name(),"action_change_state", xr_motivator.storage[object:id()].state)
	action:add_precondition		(world_property(stalker_ids.property_alive, 	true))
	action:add_precondition		(world_property(stalker_ids.property_enemy,	false))
	action:add_precondition		(world_property(properties["state_end"],	false))
	action:add_effect 		(world_property(properties["state_end"],	true))
	manager:add_action (operators["state"], action)

	action = this.action_stand_up (object:name(),"action_stand_up", xr_motivator.storage[object:id()].state)
	action:add_precondition		(world_property(stalker_ids.property_alive, 	true))
	action:add_precondition		(world_property(properties["stand"],		false))
	action:add_effect 		(world_property(properties["stand"],		true))
	manager:add_action (operators["stand"], action)

	action = manager:action (stalker_ids.action_puzzle_solver)	
	action:add_precondition		(world_property(properties["state_end"],	true))

	action = manager:action (stalker_ids.action_combat_planner)	
	action:add_precondition		(world_property(properties["stand"],		true))
end