function set_storyline(object, char_ini)
	local actor = level.actor()

    	-- Реакция на бобика
    	if char_ini:section_exist ("bobik") == true and
       	   char_ini:line_exist("bobik", "enabled") == true and
           char_ini:r_bool("bobik", "enabled") == true
    	then
        	escape_bobik.add_to_binder(object)
    	end


	-- Настройка бандитов на заводе (escape)
	xr_motivator.storage[object:id()].escape_factory_bandit = {
        	enabled  = false
	}
    	if( char_ini:section_exist ("escape_factory_bandit") ) then
        	xr_motivator.storage[object:id()].escape_factory_bandit.enabled = true
    	end
	--Настройка схемы реакции новичка3 - новичок которого ограбили
		xr_motivator.storage[object:id()].novice3 = {
                	path     = nil,         --Путь, по которому ходить
                        enemy_path = nil,       --Нулевая точка пути, туда, куда надо бежать
                        say_kill = false,       --Ни разу не говорил, что убьет бандитов
                        enabled  = false
                }
    	if char_ini:section_exist ("novice3") == true and
	   actor ~= nil and
	   actor:dont_has_info("escape_factory_bandits_dead")	
	then
        	if( char_ini:line_exist("novice3", "path") == true ) then
            		xr_motivator.storage[object:id()].novice3.path   = char_ini:r_string("novice3", "path")
        	end
        	if( char_ini:line_exist("novice3", "enemy_path") == true ) then
           		xr_motivator.storage[object:id()].novice3.enemy_path  = patrol(char_ini:r_string("novice3", "enemy_path") )
        	end
                xr_motivator.storage[object:id()].novice3.enabled = true            --Если есть секция новичка, то включаем эту схему
	    	object:set_start_dialog("loser_hello_dialog")
	    	xr_trivial.add_novice3    (object)
    	end


	-- Бандиты на свалке в гараже
	xr_motivator.storage[object:id()].robber = {
  		enabled = false,
    		leader = false,
    		helper = false,
        	path_rob = nil
    	}
    	if char_ini:section_exist ("robber") == true then
        	if char_ini:line_exist("robber", "enabled") == true then
                	xr_motivator.storage[object:id()].robber.enabled = char_ini:r_bool("robber", "enabled")
        	end
        	if char_ini:line_exist("robber", "leader") == true then
                	xr_motivator.storage[object:id()].robber.leader = char_ini:r_bool("robber", "leader")
        	end
        	if char_ini:line_exist("robber", "helper") == true then
                	xr_motivator.storage[object:id()].robber.helper = char_ini:r_bool("robber", "helper")
        	end
        	if char_ini:line_exist("robber", "path_rob") == true then
                	xr_motivator.storage[object:id()].robber.path_rob = char_ini:r_string("robber", "path_rob")
        	end
    	end
	if xr_motivator.storage[object:id()].robber.enabled == true and
	   actor ~= nil and
	   actor:dont_has_info("garbage_robber_processed")
	then
		xr_robbers.add_to_binder  (object)
	end






--Настройка схемы реакции новичка
xr_motivator.storage[object:id()].novice = {
                            path     = nil,         --Путь, по которому ходить
                            rest     = nil,         --Места для сидения
                            curState = 1,
                            time     = nil,
                            index    = 1,           --Index точки, к которой идем, чтоб посидеть
                            enabled  = false
}
    if( char_ini:section_exist ("novice") == true ) then
        xr_motivator.storage[object:id()].novice.enabled = true            --Если есть секция новичка, то включаем эту схему
        if( char_ini:line_exist("novice", "path") == true ) then
            xr_motivator.storage[object:id()].novice.path   = char_ini:r_string("novice", "path")
        end
        if( char_ini:line_exist("novice", "rest") == true ) then
            xr_motivator.storage[object:id()].novice.rest_w = patrol(char_ini:r_string("novice", "rest"))
        end
	    xr_trivial.add_novice     (object)
    end
--Настройка схемы реакции новичка2 - новичок возле аномалии
xr_motivator.storage[object:id()].novice2 = {
                            path     = nil,         --Путь, по которому ходить
                            curState = 1,
                            time     = nil,
                            artifact = nil,			--Артифакт, который пытаемся достать
                            zone     = nil,			--Зона в которой лежит артефакт
                            radius   = nil,			--Радуис зоны
                            enabled  = false
}
    if( char_ini:section_exist ("novice2") == true ) then
        xr_motivator.storage[object:id()].novice2.enabled = true            --Если есть секция новичка, то включаем эту схему

        if( char_ini:line_exist("novice2", "path") == true ) then
            xr_motivator.storage[object:id()].novice2.path     = char_ini:r_string("novice2", "path")
        end
        if( char_ini:line_exist("novice2", "artifact") == true ) then
            xr_motivator.storage[object:id()].novice2.artifact = char_ini:r_string("novice2", "artifact")
        end
        if( char_ini:line_exist("novice2", "zone") == true ) then
            xr_motivator.storage[object:id()].novice2.zone     = char_ini:r_string("novice2", "zone")
        end
        if( char_ini:line_exist("novice2", "radius") == true ) then
            local way = patrol(char_ini:r_string("novice2", "radius") )
            xr_motivator.storage[object:id()].novice2.radius   = way:point(0):distance_to(way:point(1))
        end
        xr_trivial.add_novice2    (object)
    end

--Настройка сталкера зомби
xr_motivator.storage[object:id()].zombie =
 						{
                            path     = nil,         --Путь, по которому ходить
                            curState = 1,
                            time     = 0,
                            stand    = false,
                            enabled  = false
						}
    if( char_ini:section_exist ("zombie") == true ) then
        if( char_ini:line_exist("zombie", "path") == true ) then
            xr_motivator.storage[object:id()].zombie.path = char_ini:r_string("zombie", "path")
        end
        xr_motivator.storage[object:id()].zombie.enabled = true
        xr_trivial.add_zombie(object)
	end

    escape_factory_bandits.add_to_binder(object)

end