----------------------------------------------------------------------------------------------------------------------
--Actions
----------------------------------------------------------------------------------------------------------------------
-- Обычное поведение

class "action_process_use"

function action_process_use:__init(obj, storage)
	self.object = obj
	self.st = storage
end

function action_process_use:use_callback(victim, who)
	printf("[%s] used by [%s]", victim:name(), who:name())

	if db.storage[self.object:id()].active_scheme then
		if db.actor then
			if xr_logic.try_switch_to_another_section(victim, self.st, db.actor) then
				return
			end
		end
	end
end

----------------------------------------------------------------------------------------------------------------------
-- binder
----------------------------------------------------------------------------------------------------------------------
function add_to_binder(npc, ini, scheme, section, storage) 	
	local action = this.action_process_use(npc, storage)
	storage.action = action
end

function set_use_checker(npc, ini, scheme, section)
	local st = xr_logic.assign_storage_and_bind(npc, ini, scheme, section)
	st.logic = xr_logic.cfg_get_switch_conditions(ini, section, npc)

	npc:set_callback(callback.use_object, st.action.use_callback, st.action)
end

function disable_scheme(npc, scheme)
	npc:set_callback(callback.use_object, nil)
end

