
------------------------------------------------------------------------------------------
-- misc functions
------------------------------------------------------------------------------------------
function send_sos (npc)
    local act = level.actor ()
    if act == nil or  act:alive () == false or npc:relation (act) == game_object.enemy then
       return 
    end
        
    if distance_between (npc, act) > 70.0  then
       return 
    end
    
    news_manager.send_help (act)    
end
------------------------------------------------------------------------------------------
-- Property's
------------------------------------------------------------------------------------------
 
------------------------------------------------------------------------------------------
class "evaluator_enable" (property_evaluator) 
------------
function evaluator_enable:__init (name, storage) super (nil, name)
    self.a = storage
end
------------
function evaluator_enable:evaluate ()
    return true 
end    
------------------------------------------------------------------------------------------



------------------------------------------------------------------------------------------
class "evaluator_medikit" (property_evaluator)
------------
function evaluator_medikit:__init (name, storage) super (nil, name)
    self.a = storage
end
------------
function evaluator_medikit:evaluate ()
    return self.object:object ("medkit") ~= nil
end
------------------------------------------------------------------------------------------



------------------------------------------------------------------------------------------
class "evaluator_wound" (property_evaluator) 
------------
function evaluator_wound:__init (name, storage) super (nil, name)
    self.a = storage
end
------------
function evaluator_wound:evaluate ()
	local overrides = xr_logic.generic_scheme_overrides (self.object)
	if overrides ~= nil and overrides.wounded_enabled == false then
  	   return false
	end

    if self.object.health < self.a.hp_max then
       return true
    end
    return false    
end
------------------------------------------------------------------------------------------



------------------------------------------------------------------------------------------
class "evaluator_sit" (property_evaluator) 
------------
function evaluator_sit:__init (name, storage) super (nil, name)
    self.a = storage
end
------------
function evaluator_sit:evaluate ()
    return self.a.sit
end
------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------
class "evaluator_final" (property_evaluator) 
------------
function evaluator_final:__init (name, storage) super (nil, name)
    self.a = storage
end
------------
function evaluator_final:evaluate ()
    if self.object.health < self.a.hp_max and self.a.ignore_time == 0 then 
       self.a.final = false 
    end
    return self.a.final
end
------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------
class "evaluator_cover" (property_evaluator) 
------------
function evaluator_cover:__init (name, storage) super (nil, name)
    self.a = storage
end
------------
function evaluator_cover:evaluate ()
    return self.a.cover
end
------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------
class "evaluator_friend" (property_evaluator) 
------------
function evaluator_friend:__init (name, storage) super (nil, name)
    self.a = storage
end
------------
function evaluator_friend:evaluate ()

	local vtable = self.object:not_yet_visible_objects ()
	if vtable == nil then return false end
	
	local dist = 100000.0
	local npc = nil
	
	for v in vtable do
		local vo = v:object ()
		if v.value > 0.25 * self.object:visibility_threshold () then
		   local type = object_type (vo)
		   if type == "stalker" then
		      if dist > distance_between (self.object, vo) then
		         dist = distance_between (self.object, vo)
		         npc = vo
		      end   
		   end    
        end
	end
	
	if npc == nil then return false end
	self.a.npc = npc
	if self.object:relation (npc) == game_object.enemy then return false end
	return true
		
end
------------------------------------------------------------------------------------------



------------------------------------------------------------------------------------------
class "action_cover" (action_base)
------------
function action_cover:__init (name, storage) super (nil, name)
    self.a = storage
    self.pos = vector ():set (0, 0, 0)
    self.vid = -1
    self.stage = 0
    self.dir = vector ():set (0, 0, 0)
end
------------
function action_cover:initialize ()
    action_base.initialize (self)
    
    local pt = self.object:safe_cover (self.object:position (), 20, 0)
    if pt == nil or self.object.health < self.a.hp_min then
       self.pos = self.object:position ()
       self.vid = self.object:level_vertex_id ()
    else
       self.pos = pt:position ()
       self.vid = pt:level_vertex_id ()    
    end    

    if self.object:active_item () ~= nil then
       self.object:set_item (object.deactivate, self.object:active_item ())
    end   
    
    self.object:set_node_evaluator        ()
    self.object:set_path_evaluator        ()
    self.object:set_desired_position      (self.pos)
    self.object:set_desired_direction     ()
    self.object:set_detail_path_type      (move.line)
    self.object:set_body_state            (move.standing)
    self.object:set_path_type             (game_object.level_path)
    self.object:set_dest_level_vertex_id  (self.vid)
    self.object:set_movement_type         (move.walk)
    self.object:set_mental_state          (anim.free)
    self.object:set_sight                 (look.path_dir, nil, 0)
    
    self.stage = 0
end
------------
function action_cover:execute ()
    action_base.execute (self)
    if self.stage == 0 then
       if self.object:level_vertex_id () == self.vid and self.pos:distance_to (self.object:position ()) < 1.0 then
          if self.object.health < self.a.hp_min then 
             self.object:set_sight (look.direction, self.object:direction (), 0)
             self.a.cover = true
             return
          end   
          self.stage = 1
          self.dir = vector_rotate_y (self.object:direction (), 170.0)
          self.object:set_sight (look.direction, self.dir, 0)
          return
       end    
    end
    
    if self.stage == 1 then
       if yaw_degree (self.dir, self.object:direction ()) < 5 then
          self.a.cover = true
       end
    end      
end    
------------
function action_cover:finalize ()
    action_base.finalize (self)
    self.stage = 0
end    
------------------------------------------------------------------------------------------

class "action_clear" (action_base)
------------
function action_clear:__init (name, storage) super (nil, name)
    self.a = storage
end
------------
function action_clear:initialize ()
    action_base.initialize (self)
end
------------
function action_clear:execute ()
    action_base.execute (self)
    self.a.ignore_time = device ():time_global ()
    self.a.final = true
end    
------------
function action_clear:finalize ()
    action_base.finalize (self)
end    
------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------
class "action_sit" (action_base)
------------
function action_sit:__init (name, storage) super (nil, name)
    self.a = storage
end
------------
function action_sit:initialize ()
    action_base.initialize (self)
    self.object:set_movement_type         (move.stand)
    if self.object:active_item () ~= nil then
       self.object:set_item (object.deactivate, self.object:active_item ())
    end   
    self.object:add_animation ("waunded_sitdawn_0", true)
    --self.object:add_animation ("waunded_perehod_0", true)
    self.object:add_animation ("waunded_idle_0", true)
end
------------
function action_sit:execute ()
    action_base.execute (self)
    if self.object:animation_count () == 1 then 
       self.a.sit = true
       local act = level.actor ()
       if act ~= nil and  act:alive () == true and self.object:relation (act) ~= game_object.enemy then
          level.map_add_object_icon (self.object, "wounded", "Need a medikit !!! Help !!!", 0, 0)
       end   
       if self.a.on_sit_info ~= nil then
          xr_logic.pick_section_from_condlist (level.actor (), self.object, self.a.on_sit_info.condlist)
       end 
    end    
end    
------------
function action_sit:finalize ()
    action_base.finalize (self)
    self.object:add_animation ("waunded_idle_0", true)
end    
------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------
class "action_idle" (action_base)
------------
function action_idle:__init (name, storage) super (nil, name)
    self.a = storage
   	self.sounds = 
   	            { rnd = 100,
				  maxidle = 5, 
				  sumidle = 2,
				  themes = { "help" } 
				}
    self.send_time = 0;
    self.actor = nil	
end
------------
function action_idle:initialize ()
    action_base.initialize (self)
    self.object:set_movement_type         (move.stand)
    self.object:add_animation ("waunded_idle_0", true)
    xr_meet.override_meet (self.object, true)
    self.send_time = device ():time_global ()
end
------------
function action_idle:execute ()
    action_base.execute (self)
    if self.object:animation_count () < 2 then 
       self.object:add_animation ("waunded_idle_0", true)
    end    
    xr_sound.sound_update(self.object, self.sounds)		
    
    --if self.a.on_medikit ~= nil then
       --self.object:give_info_portion_via_pda (self.a.on_medikit.info, level.actor ())
    --end   
    if device ():time_global () - self.send_time > 15000 then    
       this.send_sos (self.object)
		--if self.actor ~= nil then
			--news_manager.send_help(self.actor)
		--else
			--self.actor = level.actor()
		--end
       
       self.send_time = device ():time_global ()
    end   
end    
------------
function action_idle:finalize ()
    action_base.finalize (self) 
    xr_meet.override_meet (self.object, false)
end    
------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------
class "action_help" (action_base)
------------
function action_help:__init (name, storage) super (nil, name)
    self.a = storage
    self.first = false
   	self.sounds = 
   	            { rnd = 100,
				  maxidle = 5, 
				  sumidle = 2,
				  themes = { "help_see" } 
				}
    self.send_time = 0
    self.actor = nil
end
------------
function action_help:initialize ()
    action_base.initialize (self)
    self.object:set_movement_type         (move.stand)
    self.first = false
    self.object:enable_talk ()
    if self.a.dialog == nil then
       self.object:set_start_dialog ("tutorial_wounded")
    else
       self.object:set_start_dialog (self.a.dialog)    
    end   
    xr_meet.override_meet (self.object, true)
    self.send_time = device ():time_global ()
end
------------
function action_help:execute ()
    action_base.execute (self)
    
    if distance_between (self.object, self.a.npc) < 40 and self.first == false then
       if self.object:active_sound_count () ~= 0 then
          return 
       end     
       self.first = true
       self.object:clear_animations ()
       self.object:add_animation ("waunded_ruka_0", true)
       xr_sounds.play_sound (self.object, 1500, "wounded", 2)
    end
        
    if self.object:animation_count () < 2 then 
       self.object:add_animation ("waunded_idle_0", true)
    end    

    --if self.object:active_sound_count() == 0 then
	   xr_sound.sound_update(self.object, self.sounds)		
	--end
    if device ():time_global () - self.send_time > 15000 then    
       this.send_sos (self.object) 
   		--if self.actor ~= nil then
			--news_manager.send_help(self.actor)
		--else
			--self.actor = level.actor()
		--end
       self.send_time = device ():time_global ()
    end   
    
end    
------------
function action_help:finalize ()
    action_base.finalize (self)
    xr_meet.override_meet (self.object, false)
end    
------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------
class "action_stand" (action_base)
------------
function action_stand:__init (name, storage) super (nil, name)
    self.a = storage
    self.first = false
end
------------
function action_stand:initialize ()
    action_base.initialize (self)
    self.stage = 0
    xr_meet.override_meet (self.object, true)
    if self.a.on_medikit ~= nil then
       xr_logic.pick_section_from_condlist (level.actor (), self.object, self.a.on_medikit.condlist) 
    end   
end
------------
function action_stand:execute ()
    action_base.execute (self)
    
    if self.stage == 0 then
       printf ("STAGE 0")
       self.stage = 1
       self.object:clear_animations ()
       self.object:add_animation ("waunded_stand_up_0", true)
       return
    end
    
    if self.stage == 1 then
       printf ("STAGE 2")
       if self.object:animation_count () == 0 then
          self.stage = 2
          local act = level.actor ()
          if act ~= nil and  act:alive () == true and self.object:relation (act) ~= game_object.enemy then
             level.map_remove_object_icon (self.object)
          end 
       else
          return
       end      
    end    
    
    if self.object:is_talking () == true then
       printf ("STAGE 3")
       xr_state.anim_update ("idle", self.object) 
    else 
       self.object:eat (self.object:object ("medkit"))    
    end   
end    
------------
function action_stand:finalize ()
    if self.a.on_medikit ~= nil then
       xr_logic.pick_section_from_condlist (level.actor (), self.object, self.a.on_medikit.condlist)
    end 
    
    xr_meet.override_meet (self.object, false)
    self.object:restore_default_start_dialog ()
    action_base.finalize (self)
    self.a.sit = false
end    
------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------
class "action_enemy" (action_base)
------------
function action_enemy:__init (name, storage) super (nil, name)
    self.a = storage
    self.first = false
   	self.sounds = 
   	            { rnd = 100,
				  maxidle = 5, 
				  sumidle = 2,
				  themes = { "help_see" } 
				}
    self.send_time = 0
    self.actor = nil
end
------------
function action_enemy:initialize ()
    action_base.initialize (self)
    self.object:set_movement_type         (move.stand)
    self.object:clear_animations ()
    self.object:set_mental_state          (anim.danger)
    self.object:set_body_state            (move.crouch)
    if self.object:active_item () == nil then
       self.object:set_item (object.activate, self.object:best_weapon ())
    end   
    xr_meet.override_meet (self.object, true)
    
    self.send_time = device ():time_global ()
end
------------
function action_enemy:execute ()
    action_base.execute (self)
    
    local enemy = self.object:best_enemy ()
    if distance_between (self.object, enemy) < 20 and self.object:see (self.object:best_enemy ()) and self.object:see (enemy) == true then
       self.object:set_sight (look.fire_point, enemy:position (), 0)
       self.object:set_item (object.fire1, self.object:best_weapon ()) 
       if self.object:active_sound_count () ~= 0 then
          return 
       end     
    end
    
    xr_sound.sound_update(self.object, self.sounds)		
    
    if device ():time_global () - self.send_time > 15000 then    
       this.send_sos (self.object) 
       self.send_time = device ():time_global ()
    end   
end    
------------
function action_enemy:finalize ()
    action_base.finalize (self)
    self.object:set_item (object.deactivate, self.object:best_weapon ()) 
    self.object:clear_animations ()
    self.object:add_animation ("waunded_idle_0", true)
    xr_meet.override_meet (self.object, false)
end    
------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------
class "action_medkit" (action_base)
------------
function action_medkit:__init (name, storage) super (nil, name)
end
------------
function action_medkit:initialize ()
    action_base.initialize (self)
end
------------
function action_medkit:execute ()
    action_base.execute (self)
    self.object:eat (self.object:object ("medkit"))
end
------------
function action_medkit:finalize ()    
    action_base.finalize (self)
end    
    



------------------------------------------------------------------------------------------
function add_to_binder (object, ini, scheme, section, st)

    printf ("XR_WOUNDED:ADD_TO_BINDER CALLED")
    local operators     = {}
    local properties    = {}
    
    --local st = xr_motivator.storage[object:id()].wounded
    
    properties["enable"]        =   xr_evaluators_id.sidor_wounded_base + 0
    properties["wound"]         =   xr_evaluators_id.sidor_wounded_base + 1
    properties["sit"]           =   xr_evaluators_id.sidor_wounded_base + 2
    properties["friend"]        =   xr_evaluators_id.sidor_wounded_base + 3
    properties["cover"]         =   xr_evaluators_id.sidor_wounded_base + 4
    properties["medikit"]       =   xr_evaluators_id.sidor_wounded_base + 5
	properties["contact"]		=   xr_evaluators_id.stohe_meet_base + 1         
    
    operators["cover"]          =   xr_actions_id.sidor_act_wounded_base + 0
    operators["sit"]            =   xr_actions_id.sidor_act_wounded_base + 1
    operators["idle"]           =   xr_actions_id.sidor_act_wounded_base + 2
    operators["help"]           =   xr_actions_id.sidor_act_wounded_base + 3
    operators["friend"]         =   xr_actions_id.sidor_act_wounded_base + 4
    operators["enemy"]          =   xr_actions_id.sidor_act_wounded_base + 5
    operators["clear"]          =   xr_actions_id.sidor_act_wounded_base + 6
    operators["stand"]          =   xr_actions_id.sidor_act_wounded_base + 7
    operators["medkit"]         =   xr_actions_id.sidor_act_wounded_base + 8
    
    
    local manager = object:motivation_action_manager ()
    manager:add_evaluator (properties["enable"],    this.evaluator_enable       ("enabled", st))
    manager:add_evaluator (properties["wound"],     this.evaluator_wound        ("wound", st))
    manager:add_evaluator (properties["sit"],       this.evaluator_sit          ("sit_down", st))
    manager:add_evaluator (properties["friend"],    this.evaluator_friend       ("see_friend", st))
    manager:add_evaluator (properties["cover"],     this.evaluator_cover        ("in_cover", st))
    manager:add_evaluator (properties["medikit"],   this.evaluator_medikit      ("medikit", st))

    local action = this.action_cover ("action_cover", st)
    action:add_precondition (world_property (stalker_ids.property_alive,    true))
    action:add_precondition (world_property (stalker_ids.property_enemy,    false))
    action:add_precondition (world_property (properties["enable"],          true))
    action:add_precondition (world_property (properties["medikit"],         false))
    action:add_precondition (world_property (properties["wound"],           true))
    action:add_precondition (world_property (properties["cover"],           false))
    action:add_precondition (world_property (properties["sit"],             false))
	action:add_precondition (world_property(properties["contact"],	        false))
    action:add_effect       (world_property (properties["cover"],           true))
   	manager:add_action      (operators["cover"], action)

    action = this.action_sit ("action_sit", st)
    action:add_precondition (world_property (stalker_ids.property_alive,    true))
    action:add_precondition (world_property (properties["enable"],          true))
    action:add_precondition (world_property (properties["wound"],           true))
    action:add_precondition (world_property (properties["medikit"],         false))
    action:add_precondition (world_property (properties["cover"],           true))
    action:add_precondition (world_property (properties["sit"],             false))
    action:add_effect       (world_property (properties["sit"],             true))
   	manager:add_action      (operators["sit"], action)
    
    action = this.action_idle ("action_idle", st)
    action:add_precondition (world_property (stalker_ids.property_alive,    true))
    action:add_precondition (world_property (stalker_ids.property_enemy,    false))
    action:add_precondition (world_property (properties["enable"],          true))
    action:add_precondition (world_property (properties["wound"],           true))
    action:add_precondition (world_property (properties["medikit"],         false))
    action:add_precondition (world_property (properties["cover"],           true))
    action:add_precondition (world_property (properties["friend"],          false))
    action:add_precondition (world_property (properties["sit"],             true))
    action:add_effect       (world_property (properties["medikit"],         true))
   	manager:add_action      (operators["idle"], action)

    action = this.action_help ("action_help", st)
    action:add_precondition (world_property (stalker_ids.property_alive,    true))
    action:add_precondition (world_property (stalker_ids.property_enemy,    false))
    action:add_precondition (world_property (properties["enable"],          true))
    action:add_precondition (world_property (properties["wound"],           true))
    action:add_precondition (world_property (properties["medikit"],         false))
    action:add_precondition (world_property (properties["cover"],           true))
    action:add_precondition (world_property (properties["friend"],          true))
    action:add_precondition (world_property (properties["sit"],             true))
    action:add_effect       (world_property (properties["medikit"],         true))
   	manager:add_action      (operators["help"], action)

    action = this.action_stand ("action_stand", st)
    action:add_precondition (world_property (stalker_ids.property_alive,    true))
    action:add_precondition (world_property (stalker_ids.property_enemy,    false))
    action:add_precondition (world_property (properties["enable"],          true))
    action:add_precondition (world_property (properties["wound"],           true))
    action:add_precondition (world_property (properties["medikit"],         true))
    action:add_precondition (world_property (properties["cover"],           true))
    action:add_precondition (world_property (properties["sit"],             true))
    action:add_effect       (world_property (properties["wound"],           false))
   	manager:add_action      (operators["stand"], action)

    action = this.action_enemy ("action_enemy", st)
    action:add_precondition (world_property (stalker_ids.property_alive,    true))
    action:add_precondition (world_property (stalker_ids.property_enemy,    true))
    action:add_precondition (world_property (properties["enable"],          true))
    action:add_precondition (world_property (properties["medikit"],         false))
    action:add_precondition (world_property (properties["wound"],           true))
    action:add_precondition (world_property (properties["cover"],           true))
    action:add_precondition (world_property (properties["sit"],             true))
    action:add_effect       (world_property (properties["sit"],             false))
   	manager:add_action      (operators["enemy"], action)
   	
   	action = this.action_medkit ("action_medkit", st)
    action:add_precondition (world_property (stalker_ids.property_alive,    true))
    action:add_precondition (world_property (properties["enable"],          true))
    action:add_precondition (world_property (properties["wound"],           true))
    action:add_precondition (world_property (properties["medikit"],         true))
    --action:add_precondition (world_property (properties["cover"],           false))
    action:add_precondition (world_property (properties["sit"],             false))
    action:add_effect       (world_property (properties["wound"],           false))
   	manager:add_action      (operators["medkit"], action)
    
    action = manager:action (xr_actions_id.alife)
    action:add_precondition (world_property (properties["wound"],  false))
    
    action = manager:action (stalker_ids.action_combat_planner)
    action:add_precondition (world_property (properties["sit"],  false))

end
------------
function set_wounded (object, ini, scheme, section)

	local st = xr_logic.assign_storage_and_bind (object, ini, scheme, section)
    	
    --if section ~= nil then    	
       st.on_medikit = xr_logic.cfg_get_condlist (char_ini, section, "on_medikit", object)
	   st.dialog  = utils.cfg_get_string (char_ini, section, "dialog", object, false, "")
       st.on_sit_info = xr_logic.cfg_get_condlist (char_ini, section, "on_sit", object)
       st.hp_min = utils.cfg_get_number (char_ini, section, "hp_min", object, false, 10)
       st.hp_max = utils.cfg_get_number (char_ini, section, "hp_max", object, false, 20)
    --else
       --st.on_medikit = nil
	   --st.dialog  = nil
       --st.on_sit_info = nil
       --st.hp_min = 10
       --st.hp_max = 20
    --end       
    if st.hp_min >= st.hp_max then
       abort ("WOUNDED SCHEME IS NOT WORKING WHILE hp_min MORE OR EQUAL THAN hp_max !!! Object %s", npc:name ())
    end
    st.hp_min = st.hp_min / 100.0
    st.hp_max = st.hp_max / 100.0
    st.sit = false
    st.cover = false
    st.ignore_time = 0
    
end
