function yantar_give_bad_psy_helmet(first_speaker, second_speaker)
	local bad_helmet = second_speaker:object("bad_psy_helmet")
	if bad_helmet then
		dialogs.relocate_item(second_speaker, bad_helmet, "in")
	end
end
function yantar_give_good_psy_helmet(first_speaker, second_speaker)
	local good_helmet = second_speaker:object("good_psy_helmet")
	if good_helmet then
		dialogs.relocate_item(second_speaker, good_helmet, "in")
	end
end