-- Originally written by Lestat
-- Rewritten using classes by Zmey
-- 
-- Используются:
-- m_stalker_wounded
-- wpn_wounded

-- Имена звуковых файлов
local snd_prefix =                    [[scripts\Rolik\stalker_wounded\]]

function main ()
	debug_script_name = zmey_gameplay_1.script_name()
	debug_log(zmey_gameplay_1.script_name(), "SCRIPT ACTIVATED: zmey_gameplay_1")

	-- Для описания аргументов см. комментарий к функции set в файле classes.script
	--dlg_podoidi:set({false}, 0, 1, snd_prefix .. "wounded-01", {3000}, "govor_1", anim.danger) -- подойди

	-- 1) Подойди 2) Подойди ближе 3) Кашляет 4) Да подойди же ближе! 5) Ты должен выслушать меня 6) Стонет и кашляет
	dlg_podoidi = classes.DialogueFSM()
	dlg_podoidi:set({false      }, 0, 1, snd_prefix .. "wounded-01",   {3000},       "govor_1")              -- подойди
	dlg_podoidi:set({false, true}, 1, 2, snd_prefix .. "wounded-02",   {2000},       "zavet")                -- подойжи ближе
	dlg_podoidi:set({false      }, 2, 3, snd_prefix .. "wounded-16-1", {2000},       "idle_raneniy")         -- кашель1
	dlg_podoidi:set({false      }, 3, 4, snd_prefix .. "wounded-06",   {},           "govor_9",   "pause_6") -- да подойди же ближе
	dlg_podoidi:set({false      }, 4, 5, snd_prefix .. "wounded-07",   {},           "govor_8",   "pause_7") -- ты должен выслушать меня!
 	dlg_podoidi:set({false      }, 5, 5, snd_prefix .. "wounded-16-1", {2000, 5000}, "idle_raneniy")
	dlg_podoidi:set({false      }, 5, 5, snd_prefix .. "wounded-16-2", {2000, 5000}, "idle_raneniy")
	dlg_podoidi:set({false      }, 5, 5, snd_prefix .. "wounded-16-3", {2000, 5000}, "idle_raneniy")
	dlg_podoidi:set({false      }, 5, 5, snd_prefix .. "wounded-16-4", {2000, 5000}, "idle_raneniy")
	dlg_podoidi:set({false      }, 5, 5, snd_prefix .. "wounded-16-5", {2000, 5000}, "idle_raneniy")
	dlg_podoidi:set({false      }, 5, 5, snd_prefix .. "wounded-16-6", {2000, 5000}, "idle_raneniy")
	dlg_podoidi:set({false      }, 5, 5, snd_prefix .. "wounded-17-1", {2000, 5000}, "kashel_1")
	dlg_podoidi:set({false      }, 5, 5, snd_prefix .. "wounded-17-2", {2000, 5000}, "kashel_2")
	dlg_podoidi:set({false      }, 5, 5, snd_prefix .. "wounded-18-1", {2000, 5000}, "kashel_1")
	dlg_podoidi:set({false      }, 5, 5, snd_prefix .. "wounded-18-2", {2000, 5000}, "kashel_2")
	dlg_podoidi:set({false      }, 5, 6, snd_prefix .. "wounded-19-2", {0},          "kashel_3")
	dlg_podoidi:set({false      }, 6, 5, snd_prefix .. "wounded-19-1", {2000, 5000}, "kashel_4")

	dlg_postoi = classes.DialogueFSM()
	dlg_postoi:set({false, true}, 0, 1, snd_prefix .. "wounded-03",    {1000},      "zavet")              -- постой!
	dlg_postoi:set({false, true}, 0, 1, snd_prefix .. "wounded-04",    {1000},      "zavet")              -- остановись!
	dlg_postoi:set({false      }, 1, 2, snd_prefix .. "wounded-05",    {0},         "govor_1")            -- не оставляй меня!

	dlg_5metrov = classes.DialogueFSM()
	dlg_5metrov:set({false      }, 0, 1, snd_prefix .. "wounded-08",   {1000},      "govor_1")            -- ты должен добить Пса
	dlg_5metrov:set({false      }, 1, 2, snd_prefix .. "wounded-09",   {10},        "govor_2")            -- он свалился с моста
	dlg_5metrov:set({false      }, 2, 3, snd_prefix .. "wounded-10",   {},          "govor_3", "pause_1") -- во время атаки мутантов
	dlg_5metrov:set({false      }, 3, 4, snd_prefix .. "wounded-11",   {},          "govor_4", "pause_2") -- забери артефакт
	dlg_5metrov:set({false      }, 4, 5, snd_prefix .. "wounded-12",   {},          "govor_5", "pause_3") -- и отнеси торговцу... он ждет
	dlg_5metrov:set({false      }, 5, 6, snd_prefix .. "wounded-13",   {},          "govor_6", "pause_4") -- забирай патроны и уходи
	dlg_5metrov:set({false      }, 6, 7, snd_prefix .. "wounded-14",   {},          "govor_7", "pause_5") -- мне уже не поможешь

----------------------------------------------------------------------------------------------------

	local c_stalker_wounded = classes.NPC(zmey_gameplay_1.script_name(), get_level_object("m_stalker_wounded"))
	c_stalker_wounded.default_anim = "idle_raneniy" -- анимация при ничего-не-деланьи
	c_stalker_wounded.look_at_target_when_talking = false -- не крутить головой в сторону жертвы при разговоре!

	-- Сразу взять под скрипт, чтобы не успел никуда убежать
	if not c_stalker_wounded.npc:get_script() then
		c_stalker_wounded.npc:script(true, zmey_gameplay_1.script_name())
	end
	
	local c_actor = classes.NPC(zmey_gameplay_1.script_name(), get_actor())

	action(c_stalker_wounded.npc, anim("idle_raneniy"), cond(cond.time_end, time_infinite))
	
	local state_none = 0
	local state_5metrov = 1
	local state_postoi = 2
	local state_podoidi = 3
	local cur_state = state_none
	
	local in_zone = false
	local was_near_stalker = false
	
	local dist_near_stalker = 3
	local dist_podoidi = 8
	local dist_postoi = 15
	
	while c_stalker_wounded.npc:alive() do
		local dist = distance_between(c_stalker_wounded.npc, c_actor.npc)
		
		if was_near_stalker and dist > dist_near_stalker then
			break
		end

		if dist <= dist_near_stalker then
			if cur_state ~= state_5metrov then
				debug_log(zmey_gameplay_1.script_name(), "_bp: STATE=state_5metrov")
				cur_state = state_5metrov
				interrupt_action(c_stalker_wounded.npc, zmey_gameplay_1.script_name())
				dlg_5metrov:reset()
				c_stalker_wounded:set_dialogue(dlg_5metrov)
				was_near_stalker = true
			end
		elseif distance_between(c_stalker_wounded.npc, c_actor.npc) <= dist_podoidi then 
			in_zone = true -- кричать "постой!" если будет уходить
			if cur_state ~= state_podoidi then
				debug_log(zmey_gameplay_1.script_name(), "_bp: STATE=state_podoidi")
				cur_state = state_podoidi
				interrupt_action(c_stalker_wounded.npc, zmey_gameplay_1.script_name())
				dlg_podoidi:reset()
				c_stalker_wounded:set_dialogue(dlg_podoidi)
			end
		elseif in_zone and distance_between(c_stalker_wounded.npc, c_actor.npc) <= dist_postoi then
			if cur_state ~= state_postoi then
				debug_log(zmey_gameplay_1.script_name(), "_bp: STATE=state_postoi")
				cur_state = state_postoi
				interrupt_action(c_stalker_wounded.npc, zmey_gameplay_1.script_name())
				dlg_postoi:reset()
				c_stalker_wounded:set_dialogue(dlg_postoi)
			end
		else
			--c_stalker_wounded.npc.health = 0
			break
		end

		if not c_stalker_wounded:is_talking() and not c_stalker_wounded:is_shooting() then
			c_stalker_wounded:talk_dialogue(c_actor.npc)
		end

		wait()
	end

	if c_stalker_wounded.npc:action() then
		c_stalker_wounded.npc:script(false, zmey_gameplay_1.script_name())
		c_stalker_wounded.npc:script(true, zmey_gameplay_1.script_name())
	end
	
	-- фразу отыграем через sound object:
	local psa_dobei = sound_object(snd_prefix .. "wounded-15")

	if c_stalker_wounded.npc:alive() then
		action_first(c_stalker_wounded.npc, anim("smert"), cond(cond.anim_end, time_infinite))
		-- Если жив, можно уже начинать играть фразу:
		--psa_dobei:play_at_pos(c_stalker_wounded.npc, c_stalker_wounded.npc:position());
		psa_dobei:play_at_pos(c_stalker_wounded.npc, c_stalker_wounded.npc:position(), 0, 0)
		GiveInfoViaPda(c_actor.npc, c_actor.npc, 1)
		-- Если мертв, то попозже (чтобы не заглушилось предсмертным криком)
	end

	
	debug_log(zmey_gameplay_1.script_name(), "_bp: Waiting for death animation to finish")
	while c_stalker_wounded.npc:action() do
		wait()
	end
	debug_log(zmey_gameplay_1.script_name(), "_bp: Death animation has finished")

	if c_stalker_wounded.npc:alive() then
		action_first(c_stalker_wounded.npc, anim("smert_end"), cond(cond.anim_end, time_infinite))
	end
	debug_log(zmey_gameplay_1.script_name(), "_bp: Waiting for final death animation to finish")

	-- Раскомментарить для отключения смерти от хита (будет лежать живым и играть анимацию мертвого)
	if true then
		while c_stalker_wounded.npc:action() do
			wait()
		end
	end

	debug_log(zmey_gameplay_1.script_name(), "_bp: Final death animation has finished")

	--GiveInfoViaPda(c_actor.npc, c_stalker_wounded.npc, 1) -- zzz delme FIXME

	if c_stalker_wounded.npc:alive() then
		local h = hit ()
		h.power = 200
		h.direction = vector ():set(0, 0, 1)
		h:bone("bip01_head")
		h.draftsman = get_actor()
		h.impulse = 0
		h.type  = hit.wound
		c_stalker_wounded.npc:hit(h)
	else
		local play_to = game.time() + 2000 -- длительность звука
		while game.time() < play_to do
			wait()
		end
		-- Еще раз:
		--psa_dobei:play_at_pos(c_stalker_wounded.npc, c_stalker_wounded.npc:position());
		psa_dobei:play_at_pos(c_stalker_wounded.npc, c_stalker_wounded.npc:position(), 0, 0)
		GiveInfoViaPda(c_actor.npc, c_actor.npc, 1)
	end

	while true do
		wait()
	end
	
	debug_log(zmey_gameplay_1.script_name(), "SCRIPT STOPPED: zmey_gameplay_1")
end

----------------------------------------------------------------------------------------------------

