//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ide2.rc
//
#define ID_EDIT_CTRL                    101
#define ID_VIEW_WORKSPACE               102
#define ID_VIEW_OUTPUT                  103
#define ID_OUTPUT_CTRL1                 104
#define ID_OUTPUT_CTRL2                 105
#define ID_OUTPUT_CTRL3                 106
#define IDB_IL_TAB                      107
#define ID_VIEW_CALLSTACK               107
#define IDB_IL_FILE                     108
#define IDC_VARIABLES                   108
#define ID_VIEW_LOCALS                  109
#define IDC_WATCHES                     110
#define ID_VIEW_WATCHES                 111
#define IDR_MAINFRAME                   128
#define IDR_IDE2TYPE                    129
#define IDR_ACCEL_BUILD                 129
#define IDR_SUBMENU_BUILD               130
#define IDR_ACCEL_DEBUG                 130
#define IDS_STRING130                   130
#define IDR_SUBMENU_DEBUG               131
#define IDR_ACCEL_DEBUG_BREAK           131
#define IDR_PROJECT_MENU                132
#define IDR_ACCEL_NO_PROJECT            132
#define IDD_DIALOG1                     136
#define IDD_DEBUG_DIALOG                137
#define IDD_DIALOG_NEW_PROJECT          140
#define IDR_MENU1                       142
#define IDC_PROJECT_TYPES               1002
#define IDC_OUTPUT_DIR                  1003
#define IDC_PROJECT_NAME                1003
#define IDC_BROWSE_FOLDER               1004
#define IDC_PROJECT_LOCATION            1004
#define IDC_OUTPUT_PREFIX               1005
#define IDC_PROJECT_SELLOC              1005
#define IDC_GENERATE_LISTING            1006
#define IDC_INTERMEDIATE_DIR            1007
#define IDC_EDIT1                       1007
#define IDC_STATIC_COMMAND              1008
#define IDC_EDIT2                       1008
#define IDC_STATIC_COMMAND2             1009
#define IDC_STATIC_COMMAND3             1010
#define IDC_EDIT_CMD                    1012
#define IDC_EDIT_WDIR                   1013
#define IDC_EDIT_ARGS                   1014
#define IDC_BUTTON1                     1015
#define IDD_SCINTILLA_FINDDLGORD        1020
#define IDD_SCINTILLA_REPLACEDLGORD     1021
#define IDC_REGULAR_EXPRESSION          1022
#define ID_DEBUG_RUNTOCURSOR            32742
#define ID_PROJECT_ADD_FILES            32771
#define ID_FILE_OPENPROJECT             32773
#define ID_FILE_SAVEPROJECT             32774
#define ID_FILE_SAVEPROJECTAS           32775
#define ID_PROJECT_PROPERTIES           32776
#define ID_BUILD_COMPILE                32777
#define ID_BUILD_BUILD                  32778
#define ID_BUILD_REBUILDALL             32779
#define ID_BUILD_CLEAN                  32780
#define ID_BUILD_GO                     32781
#define ID_BUILD_STEPINTO               32782
#define ID_BUILD_RUNTOCURSOR            32783
#define ID_BUILD_EXECUTE                32784
#define ID_DEBUG_RESTART                32785
#define ID_DEBUG_STOPDEBUGGING          32786
#define ID_DEBUG_BREAK                  32787
#define ID_DEBUG_STEPOVER               32788
#define ID_DEBUG_STEPOUT                32789
#define ID_DEBUG_STEPINTO               32792
#define ID_DEBUG_GO                     32793
#define ID_TOGGLE_BREAKPOINT            32798
#define ID_FILE_NEWPROJECT              32799
#define ID_FILE_CLOSEPROJECT            32800
#define ID_HELP_CONTACTAUTHOR           32801
#define ID_HELP_LUAHELPPDF              32802
#define ID_HELP_VISITHOMEPAGE           32803
#define ID_HELP_LUAHOMEPAGE             32804
#define ID_DEBUG_DEBUGBREAK             32805
#define IDC_THREADS                     32806
#define ID_VIEW_THREADS                 32807
#define ID_VIEW_THREADS32807            32807
#define ID_EDIT_GOTOLINE                32808
#define ID_PROJECT_DEBUGGING            32818
#define ID_PROJECT_RUNPROJECT           32819
#define IDR_TOOLS_OPTIONS               32824
#define ID_VIEW_LUARUNTIME              32825
#define ID_BUTTON32825                  32825
#define ID_BUTTON32826                  32826
#define ID_BUTTON32827                  32827
#define ID_BUTTON32828                  32828
#define ID_BUTTON32829                  32829
#define ID_BUTTON32830                  32830
#define ID_VSS_CHECKIN                  32832
#define ID_VSS_UNDOCHECKOUT             32833
#define ID_VSS_DIFFERENCE               32834
#define ID_VSS_CHECKOUT                 32835
#define ID_EDIT_FINDNEXT                32841
#define ID_FILE_SAVEALLMODIFIED         32847
#define ID_SHOW_FUNCTION_LIST           32852
#define ID_PROJECT_ADDFOLDER            32858
#define ID_VSS_GETLATESTVERSION         32859
#define ID_EDIT_COMPLETEWORD            32860
#define ID_EDIT_TOGGLEBOOKMARK          32866
#define ID_EDIT_GOTONEXTBOOKMARK        32867
#define ID_EDIT_BREAKPOINTSLIST         32874
#define ID_ADD_WATCH                    32880

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32885
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
