
function drop_(item)
	local v = vector()
	v:set(0,1,0)
	db.actor:drop_item_and_teleport(item,v)
end

function main()
db.actor:inventory_for_each(_test.drop_)

--   local h = hit ()
--   h.power = 100
--   h.direction = vector():set(0, 0, 1)
--   h.impulse = 100
--   h.draftsman = db.actor
--   h.type = hit.fire_wound
--   db.actor:hit(h)
	
--local ce = path_cam_effector("test.anm")
--local ce = path_cam_effector("camera_effects\\earthquake.anm")


--local ce = _test.some_cam_effector(1.3,7.0,10.0,5.0)
--level.add_cam_effector(ce)

--	local info = "tutorial_artefact_start" 
--	db.actor:give_info_portion(info) 
   
end
